### ISSUE TITLE
Somehow not working 

### ISSUE THREAD

**Issue by fofiedelly** [mpalourdio/ng-http-loader#1]
Hello great lib.
Howerer it's somehow not working, how am I supposed to integrate the SpinKit ?
Config: Angular 4+ and i follow your instructions
Regards.

**Comment by mpalourdio** [comment]
Hello. On holidays at the moment. But what exactly does not work? Have you for any error in your console ?

By default, simple registering the module in your application and adding the <spinner></spinner>  tags should work out if the box.

**Comment by mpalourdio** [comment]
Also check an example of integration here https://github.com/mpalourdio/SpringBootAngularHTML5/tree/master/front

**Comment by thienedits** [comment]
Yea I also can not get it to work, no error. Added what was in app.component.html, app.component.ts and app.module.ts. In dev tools <spinner></spinner> doesnt not show any appending child elements. Not sure if I missed something.

**Comment by fofiedelly** [comment]
But what exactly does not work? /// 
The spinner is not been displayed... i put like @thienedits  explains the same code like in the doc. No error or Log in the dev Tool.  Can not find out what is missing....

**Comment by mpalourdio** [comment]
Have you got some code to show me ?

Be aware that we need angular >= 4.3, nh-http-loader >=0.2.0, use the new HttpClientModule to perform your http requests etc. I'm glad to help if you can show me a project where this does not work.

**Comment by thienedits** [comment]
Yea thanks I got it to work by switching out HttpModule for the new HttpClientModule from @angular/common/http in Angular 4.3. Thanks.

**Comment by mpalourdio** [comment]
Thanks for the feedback. Looks like I should slightly improve the documentation to notify the users they need to use the new ``HttpClientModule``

**Comment by thienedits** [comment]
Can I also add that I was not able to the the backgroundColor property to work. I changed the hex value but it was always white. Also would be awesome if you could also add a property to set the color of the animation.

**Comment by mpalourdio** [comment]
Please open another issue with small code repro. please.

**Comment by thienedits** [comment]
Derp, looks like I had some other css that was changing the color of the spinkit background. Its working now, thanks for the library.

**Comment by mpalourdio** [comment]
Closing as this is mainly a documentation issue on the fact that consumers need to use the new ``HttpClientModule`` api to perform http requets
