### ISSUE TITLE
i have faced this error during production build.

### ISSUE THREAD

**Issue by lubkoKuzenko** [mpalourdio/ng-http-loader#10]
`[at-loader] Checking finished with 1 errors
Error in bail mode: [at-loader] ./node_modules/ng-http-loader/pending-interceptor.service.d.ts:7:22
    TS2420: Class 'PendingInterceptorService' incorrectly implements interface 'HttpInterceptor'.
  Types of property 'intercept' are incompatible.
    Type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>' is not assignable to type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
      Type 'Observable<HttpEvent<any>>' is not assignable to type 'Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
npm ERR! code ELIFECYCLE`

$ node -v
v8.1.2

$ npm -v
5.3.0

**Comment by mpalourdio** [comment]
Production build + module symlinked ?

**Comment by lubkoKuzenko** [comment]
this error happens after error in my eot build(error in my system) and folder compiled was created. After that all builds failed until i removed this folder manually. Thanks it's just a strange issue after build fail. Issue can be closed.

**Comment by mpalourdio** [comment]
Thanks for feedback
