### ISSUE TITLE
Compatibility with Cypress (v3.1.1)

### ISSUE THREAD

**Issue by zaarheed** [mpalourdio/ng-http-loader#100]
Does `ng-http-loader` take an extra few milliseconds to hide the spinner once a HTTP response has been received? I am noticing patchy issues around a large request and Cypress trying to find the next element before the spinner and overlay are hidden.

For example:
Say I have a button (id="button1) "which loads data when its clicked. If the call is successful a second button (id="button2") appears. I want to use Cypress to test clicking both buttons like this:

```
cy.get("#button1").click();
cy.get("#button2").click();
```

I get an error saying that #button2 could not be found. If I add a delay of 500ms between the two actions like so:
```
cy.get("#button1").click();
cy.wait(500);
cy.get("#button2").click();
```

It works every time.

I'm narrowing this down to an issue around `ng-http-loader` because this issue does not occur if I completely disabled the `ng-http-loader` spinner. But I am not yet convinced whether this is a `cypress` issue or a `ng-http-loader` issue.

In the meantime I am going to explore adding a global 500ms (or similar) delay for all events like this. But ideally, I'd like to at least know what exactly is causing the issue just in case I am overlooking something.

Cypress: [https://www.cypress.io/](https://www.cypress.io/)

**Comment by zuperm4n** [comment]
Forgot to add I am using `ng-http-loader` v3.1.1.

**Comment by zuperm4n** [comment]
@mpalourdio do you think the delay is significant enough to cause an issue with Cypress? Have you tried the spinner with any other automation tools and encountered similar issues to what is described above?

**Comment by mpalourdio** [comment]
No, I don't think this is significant TBH. Members of my QA team regularly run heavy e2e testing  suites on angular applications (selenium & co.) without any issues reported. I do not know cypress at all, sorry.

**Comment by mpalourdio** [comment]
If you button is not in the dom, I just cannot see how this module could be the cause. I do not say that you do not experience issues, but I just can't figure what could be the cause.

**Comment by zuperm4n** [comment]
@mpalourdio no worries. I'll investigate further and report back if I find anything.

The button is definitely in the DOM. Cypress lets you walk-through snapshots at every line of `e2e` tests so I can see the button has been rendered, but the spinner is still overlaying the component even though the HTTP call was completed in the previous step. It could just be an issue with how I have the spinner configured. Thanks for your help.

**Comment by mpalourdio** [comment]
I see.. Maybe some HTTP requests are still pending in background. I don't know, really.

You can still log things that happen by this `quick and dirty` way : https://github.com/mpalourdio/SpringBootAngularHTML5/blob/a99fc4582a618a580675a7c22ce4eb52c37b4070/front/src/app/app.component.ts#L22

**Comment by zaarheed** [comment]
I didn't get to the bottom of this, but for anyone else landing here, the best solution was to use `timeout`s in Cypress.

Documentation here: [https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Timeouts](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Timeouts)

**Comment by mpalourdio** [comment]
Sorry for closing this without any comment and thanks for feedback. Feel free to comment or reopen if needed
