### ISSUE TITLE
incompatible peer dependency

### ISSUE THREAD

**Issue by Santosh8055** [mpalourdio/ng-http-loader#102]
Package "ng-http-loader" has an incompatible peer dependency to "@angular/core" and "@angular/common". It requires "~7.0.0 but latest version is "~7.1.0"

**Comment by mpalourdio** [comment]
I need to give this a shot. I will release a v4 ASAP with some small fixes. It's just a warning, not something that prevents the module to be used.

**Comment by Santosh8055** [comment]
Hi Sir,

Yes, warning, but I'm not able to update angular because of this.

**Comment by mpalourdio** [comment]
angular-cli with ng 7.1.0 has not been released yet. I will release a fresh new version when this ill be the case.
you can ``yarn upgrade`` safely at the moment.
