### ISSUE TITLE
NgHttpLoader Not Dismissing ChangeDetectionStratergy.OnPush

### ISSUE THREAD

**Issue by ct5845** [mpalourdio/ng-http-loader#105]
(1) https://stackblitz.com/edit/angular-sccpib

In this example the initial http call for data, occurring in the ngOnInit of hello, doesn't trigger the loader to appear. 

(2) https://stackblitz.com/edit/angular-eejkhz

In this slight variation changeDetection = OnPush, the loader never disappears 

2. Is the problem i was finding in my app on trying to use this component, (1) just happened to notice along the way.

**Comment by mpalourdio** [comment]
1. works for me, loader is triggered on start
2. on push of course won't trigger spinner hide, you need to trigger yourself change detection.

**Comment by ct5845** [comment]
1. Yup... odd, is the delay/min duration maybe not initialised in time? Might of been happening too quickly as it was caching the call when i was editing? But ok not a problem!

2. So how would i trigger change detection here? run whatever the subscribe is in a zone.run? or just do .markForCheck/.detectChanges on every .subscribe from a HTTP call? Obviously want to use this because of the interceptors and the need *not* to have to manually show/hide HTTPClient calls, so neither of the above solutions is ideal for that need.

**Comment by mpalourdio** [comment]
1. cool
2. I don't know. Any solution you can provide to fix this (not) issue ?

**Comment by mpalourdio** [comment]
After re-reading [this blog post](https://netbasal.com/a-comprehensive-guide-to-angular-onpush-change-detection-strategy-5bac493074a4), I came to conclusion this is not a bug.

I have just modified your example by moving the change detection to HelloComponent. It works as expected.

https://stackblitz.com/edit/angular-bwgy5d

**Comment by mpalourdio** [comment]
The only relevant change that could fix this, is encapsulating the show/hide logic via an async pipe, as described in the blog post.

We had another issue like yours : https://github.com/mpalourdio/ng-http-loader/issues/57

**Comment by mpalourdio** [comment]
I have opened an issue here to track this possible, but not trivial change : https://github.com/mpalourdio/ng-http-loader/issues/106

**Comment by mpalourdio** [comment]
v 5.0.0-beta.0 published.

Faulty stackblitz forked and update : https://stackblitz.com/edit/angular-hgqhfy

**Comment by mpalourdio** [comment]
@ct5845 (hopefully) fixed in v5.0.0
