### ISSUE TITLE
Subscribe to spinner visibility Observable

### ISSUE THREAD

**Issue by EmanJasarevic** [mpalourdio/ng-http-loader#108]
Hi @mpalourdio!
Is it possible to subscribe to the visibility of `ng-http-loader`, so we can control visibility of other items based on the current spinner state?

Use case:
`app.component.html`
```
<ng-http-loader  #testSpinner
                  [spinner]="'sk-three-bounce'"
                  [debounceDelay]="150">
</ng-http-loader>
```

Some child component:
```
this.spinnerVisibilityService.isVisible$.subscribe(isVisible => {
   // Show/hide some elements on UI based on the current state of spinner
});
```

As I can see from the implementation, `SpinnerVisibilityService` has `visibility$` Observable`, but that one is used only in case when we manually show/hide spinner.

Regards

**Comment by mpalourdio** [comment]
Hello,

you're right, this observable controls manual show/hide action. You need to subscribe to ``PendingRequestsInterceptor#pendingRequestsStatus$``

See this example [here](https://github.com/mpalourdio/SpringBootAngularHTML5/blob/065af5286138a9022ad1d49d95a7a1db277011e3/front/src/app/app.component.ts#L21-L23).

**Comment by mpalourdio** [comment]
I had forgetten that from V5, there's another possible approach. There is an observable [here](https://github.com/mpalourdio/ng-http-loader/blob/32b38f8c7a328823fd47459065837f6059668abe/src/lib/components/ng-http-loader.component.ts#L75) now.

But you need to inject `NgHttpLoaderComponent` as `ViewChild` to subscribe to it. But IMO, injecting the interceptor is a better.

**Comment by EmanJasarevic** [comment]
Great! `PendingRequestsInterceptor#pendingRequestsStatus$` did the trick.
I already tried before writing this "issue" with @ViewChild approach to access that observable but NgHttpLoaderComponent was always undefined (maybe I mistyped something) 🙂 
Thx for the quick help!

**Comment by mpalourdio** [comment]
OH, I need to test this.
Thanks for letting me know !

Closing this issue for now.

**Comment by mpalourdio** [comment]
@EmanJasarevic  Can confirm that this work too, see [here](https://github.com/mpalourdio/SpringBootAngularHTML5/blob/3ab228090060dec625a51e93ce8f17311febf09b/front/src/app/app.component.ts).

It need to be done in `ngAfterViewInit` as stated before.

**Comment by EmanJasarevic** [comment]
That was the catch then. Anyway, this approach with `PendingRequestsInterceptor` works as well.
Thanks for sharing!
