### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof NgHttpLoaderModule'

### ISSUE THREAD

**Issue by byronglendon** [mpalourdio/ng-http-loader#109]
**Version:** ng-http-loader@3.0.0

**Error:** Property 'forRoot' does not exist on type 'typeof NgHttpLoaderModule'

import { NgHttpLoaderModule } from 'ng-http-loader; 

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutes,
    HttpClientModule, 
    NgHttpLoaderModule.forRoot(), // <============ No 'forRoot()'!
  ],
  providers: [],
  bootstrap: [AppComponent]
})

**Comment by mpalourdio** [comment]
The `forRoot` has been introduced in [v4](https://github.com/mpalourdio/ng-http-loader/blob/master/CHANGELOG.md#v400).
