### ISSUE TITLE
Angular 5 Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by thienedits** [mpalourdio/ng-http-loader#11]
I upgraded to angular 5 and getting this when running ng serve with angular-cli. 

This may help:
https://github.com/angular/angular-cli/issues/4647#issuecomment-307051552
https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

````
WARNING in ./~/ng-http-loader/~/@angular/core/@angular/core.es5.js
5651:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ng-http-loader/~/@angular/core/@angular/core.es5.js
5667:15-102 Critical dependency: the request of a dependency is an expression

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in C:/pub/inferno/node_modules/ng-http-loader/node_modules/@angular/core/core.d.ts, resolving symbol NgHttpLoaderModule in C:/pub/inferno/node_modules/ng-http-loader/ng-http-loader.module.d.ts, resolving symbol NgHttpLoaderModule in C:/pub/inferno/node_modules/ng-http-loader/ng-http-loader.module.d.ts
````

**Comment by thienedits** [comment]
Also tried adding enhanced-resolve as suggested in this issue but i still get same error

https://github.com/mpalourdio/ng-http-loader/issues/8

**Comment by thienedits** [comment]
I talked to one of the angular devs and he said they have a PR that will fix this soon.

https://github.com/angular/angular-cli/pull/7693

**Comment by mpalourdio** [comment]
Hello, I haven't tested anything with angular 5 at the moment. Will check it ASAP stable release is up.

**Comment by musti2** [comment]
Hi, I am on angular 4.4.4 and this fails during ng serve with the same error here.

**Comment by mpalourdio** [comment]
All ok with angular 4.4.4 and this module AFAIK. Please check this https://github.com/mpalourdio/ng-http-loader/issues/8

Any code for reproduction ?

**Comment by navrudh** [comment]
Observed this issue on angular 4.4.4. Its now fixed in angular 4.4.6

**Comment by thienedits** [comment]
@musti2  I got this once also on 4.4 but I think It went away after I ran vscode on windows as administrator. Are you on Windows?

**Comment by mpalourdio** [comment]
The module has been updated to support angular 5 && angular-cli 1.5.0 from version 0.4.0.

Can this be closed for now ?
