### ISSUE TITLE
loader not working with angular 7.2.2

### ISSUE THREAD

**Issue by mastermind3043** [mpalourdio/ng-http-loader#111]
- ng-http-loader version 4.0.0 and above does not work with angular http 7.2.2
- http requests are not intercepted, explicit usage of Spinner Visibility Service works
- Downgrading to ng-http-loader 3.2.0 works

**Comment by mpalourdio** [comment]
Of course it works ;)

**Comment by mastermind3043** [comment]
My bad for missing the forRoot(). Thanks for clarifying

**Comment by mpalourdio** [comment]
v5 is the way to go for now !
