### ISSUE TITLE
Spinner not disappearing

### ISSUE THREAD

**Issue by kosnkow** [mpalourdio/ng-http-loader#113]
Hi , I got anguler > 7 and ng-http-loader 5.0.0 
Inside web-layout.component.htm I have 
<ng-http-loader
  backgroundColor="#1b3d65"
  [spinner]="spinkit.skWave"
  [debounceDelay]="100"
  [minDuration]="200"
  [filteredHeaders]="['x-skip-http-loader']"
></ng-http-loader>

Sometimes the spinner is now showing, even after few seconds, and most of the time when request takes more then 3 seconds , spinner is not hidding, what can i check ?

**Comment by mpalourdio** [comment]
Cannot guess what could happen without full reproduction code, sorry

**Comment by kosnkow** [comment]
I have angular component, when I add <button id="myButton" (click)="test()"></button>
and inside test I add this.myService.getData$().subscribe(); and set brakepoint inside getData on the server all works fine.

now , If I add on the same component leaflet map like this
<apl-leaflet
    #leafletMap
    [geoJson]="geoJson"
    [buildingLatLng]="buildingLatLng"
    [createMarker]="createMarker"
    [showPolygonDetails]="showPolygonDetails"
    [context]="this"
    [showFloorControl]="false"
    [addPointerMessage]="translations.AddNewEquipment"
    [canAddPointers]="canAddPointers"
    (mapObjectItemAdded)="onMapObjectItemAdded($event)"
    (layerSelectorButtonClicked)="onLayerSelectorButtonClicked($event)"
    [createClusterGroup]="createClusterGroup"
    [addPolygonMessage]="translations.AddNewLocation"
    (layersLoaded)="onLayersLoaded()"
    [movingMode]="assetMovingEnabled"
  ></apl-leaflet>

and inside onMapObjectItemAdded I put this.myService.getData$().subscribe(); then spinner does not show when this method is fired, I can see that request was made, breakpoint was hit on the server, but spinner is not showing.

**Comment by mpalourdio** [comment]
I `assume` that things run outside an angular zone. But once again, I cannot provide support without a minimum and easily reproducible case.
