### ISSUE TITLE
Force Stop Loader in Component For Url

### ISSUE THREAD

**Issue by jeremysangroni** [mpalourdio/ng-http-loader#115]
Hello, I would like to know how to stop the use of the interceptor loader in a specific route, for example:

http: //localhost: 4200/admin/monitoring

**Comment by mpalourdio** [comment]
You can't do that. You must filter specific URL for HTTP requests that **are** performed, not from **where** they are performed.

**Comment by jeremysangroni** [comment]
entonces como hago amigo? solo quisiera que dentro de esta url no funcione el loader.
