### ISSUE TITLE
Destroy spinner when router changed and destroy spinner manually

### ISSUE THREAD

**Issue by TrickTrcker** [mpalourdio/ng-http-loader#12]
when server response get delayed, i changed router path and spinner not hiding. How can destroy it programmatically.

**Comment by mpalourdio** [comment]
You can use the ``pendingRequests`` observable from pendingRequests and call ``PendingInterceptorService#next(false) manually

**Comment by mpalourdio** [comment]
Closing now as it's not an issue, but a question. Feel free to re-open if an issue appears.
