### ISSUE TITLE
Not working with Angular 7

### ISSUE THREAD

**Issue by Arjun-Shinojiya** [mpalourdio/ng-http-loader#120]
I tried to implement loader in angular 7.I am gettting this error.

**Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at ng-http-loader.js:361**

**Comment by asad-c** [comment]
See the compatibility table below, make sure you don't have version 8 of the ng-http-loader package installed. Downgrade to version 7 and it should work.

ng-http-loader | Angular
-- | --
>=0.1.0 <0.4.0 | ^4.3.0
>=0.4.0 <1.0.0 | ^5.0.0
>=1.0.0 <3.2.0 | ^6.0.0
>=3.2.0 <5.1.0 | ^7.0.0
>=6.0.0 | ^8.0.0

**Comment by mpalourdio** [comment]
Thanks @asad-c , that's indeed the reason.
