### ISSUE TITLE
show spinner in one particular part of the page as a waiting tool

### ISSUE THREAD

**Issue by sadra74** [mpalourdio/ng-http-loader#121]
I want to use this spinner in just one particular part of the page. I mean that I do not want to see the whole page covered by a backdrop. If I want to put it in a better way, I should say I want to put my component under a cover until my user does something. Here is an example for you:
Assume you have a form and you have a component in the same page that shows the results after filling that form I want to put a cover on that result component until the user fill the form. Before that I want to show him a spinner after filling the form and submitting data the spinner is gone and the user can see the results so overall I want to use this spinner as a waiting tool is it possible?

**Comment by mpalourdio** [comment]
You can't do that easily at the moment. I can imageine that tt's still possible if you define your own spinner, and you disable the backdrop via options. Then, you can use a lot of CSS magic to put the spinner wherever you want.

But nothing out of the box allows this at the moment. This module is meant to be easy to plug&play. Such an option would require much more customization.
