### ISSUE TITLE
entryComponent not working

### ISSUE THREAD

**Issue by Gajendrasinh** [mpalourdio/ng-http-loader#123]
I have added my custom component but it still showing default.

<ng-http-loader [entryComponent]="SpinnerComponent"></ng-http-loader>

  entryComponents : [
    SpinnerComponent
  ],

**Comment by mpalourdio** [comment]
Full code or it didn't happen :p

**Comment by mpalourdio** [comment]
Also some examples [here](

**Comment by mpalourdio** [comment]
Closing as no feedback
