### ISSUE TITLE
Prevent loader to dim the entire screen while loading

### ISSUE THREAD

**Issue by Arjun-Shinojiya** [mpalourdio/ng-http-loader#124]
Currently, when ng-http-loader is loading in my angular project, it changes the opacity of the whole screen with loading. I don't want to change the opacity of screen while loading screen. Is there any solution for this issue. Thank you

**Comment by mpalourdio** [comment]
There's a ``backdrop`` boolean that does this in options. See https://github.com/mpalourdio/ng-http-loader#customizing-the-spinner

**Comment by Arjun-Shinojiya** [comment]
Backdrop didnt worked for me @mpalourdio .I applied this code in scss and now its working fine.
#spinner {
  opacity: 1 !important;
  background-color: transparent !important;
}

**Comment by mpalourdio** [comment]
So you're all done :) Closing now.
