### ISSUE TITLE
Fix RxJS partition operator import

### ISSUE THREAD

**Issue by fairmutex** [mpalourdio/ng-http-loader#126]
## Expected behavior

To not have errors

## Actual behavior

partition is not a function

## ng-http-loader version

 "ng-http-loader": "^6.0.1",

Import of partition from RxJS should be

import { partition } from 'rxjs/operators';
and not

import { partition } from 'rxjs';

Issue introduced [here](https://github.com/mpalourdio/ng-http-loader/commit/754be4fc797b86e9f5394d36d53ebd9f281c9bf9)

**Comment by mpalourdio** [comment]
No, the import is OK here. You should use rxjs ^6.5.0, as stated in the peerDependency section.

**Comment by fairmutex** [comment]
Yes you're right thanks.
