### ISSUE TITLE
Debounce delay and minDuration not working in Iphone.

### ISSUE THREAD

**Issue by Arjun-Shinojiya** [mpalourdio/ng-http-loader#129]
I have one page in my angular project which have multiple api calls so to avoid multiple loading in every second, I setup **minDuration** to "1500" and **debounceDelay** to "200" . It working fine in my desktop screen and in Android devices but in Iphone devices I think this attributes are not working thats why in Iphone I am facing multiple time loader hide and show issue. Please let me know if I can do anything to resolve this issue.

**Comment by mpalourdio** [comment]
I have no iPhone to test. Which iOS version and which browser ?

**Comment by Arjun-Shinojiya** [comment]
@mpalourdio  IOS version 12 and in safari browser

**Comment by mpalourdio** [comment]
Closing as I won't provide any support for a proprietary browser.
