### ISSUE TITLE
ERROR TypeError: Cannot read property 'skWave' of undefined (Spinkit)

### ISSUE THREAD

**Issue by kisonay** [mpalourdio/ng-http-loader#13]
When trying to define the spinner to use i.e. [spinner]="Spinkit.skWave" I receive the following error:

`ERROR TypeError: Cannot read property 'skWave' of undefined`

Does Spinkit need to be defined somewhere?

**Comment by mpalourdio** [comment]
yes, have a llok at  https://github.com/mpalourdio/ng2/blob/63cef2ee115cb0ba5105a635aee0a8e29a4d921b/src/app/app.component.ts#L17

**Comment by kisonay** [comment]
thank you!
