### ISSUE TITLE
Spinner not hiding

### ISSUE THREAD

**Issue by mluker** [mpalourdio/ng-http-loader#130]
Other versions:
- ng-http-loader version: 6.0.1
- Angular CLI: 8.3.14
- Node: 12.13.0
- OS: win32 x64

Angular:
- @angular-devkit/architect        0.803.14
- @angular-devkit/core               8.3.14
- @angular-devkit/schematics   8.3.14
- @schematics/angular               8.3.14
- @schematics/update                0.803.14
- rxjs                                              6.4.0

I am having an issue when I refresh any page the spinner spins and never stops. If I switch browser tabs and switch back, size the developer console window, or click on the screen, it will go away as expected. Other than that it functions as expected.

**Comment by mpalourdio** [comment]
The minimum rxjs supported version is https://github.com/mpalourdio/ng-http-loader/blob/9a38f29235bc963d77756f35a35b27337bc29a4e/package.json#L42

**Comment by mluker** [comment]
I upgraded to  "rxjs": "^6.5.3" and unfortunately I have the same issue.

**Comment by mpalourdio** [comment]
I need a small reproducible project so I can give it a check. I just can't tell what is happening without code.

**Comment by mluker** [comment]
It turns out the issue originated from using ngsx and making a service call from within an @Action. I ended up subscribing to that and just hiding the spinner when it completed.

**Comment by mpalourdio** [comment]
Thanks for letting me know!
