### ISSUE TITLE
Loader not hiding on 500 Error

### ISSUE THREAD

**Issue by sjpatel** [mpalourdio/ng-http-loader#132]
Loader should hide after a request is completed

At present, on any 500 error, the loader continues to display

setup the loader, fire an http request, if the response code is 500 the loader won't hide

V 6.0.1

Nothing works as expected on Internet explorer or Safari.

**Comment by mpalourdio** [comment]
For the moment, this is expected. It's something I'm thinking about handling in the next version, but I'm not sure if it's a good idea, as it should be done a userland level.
 
You're mostly not catching your HTTP error. As a consequence, the subjects in your application and in this module never complete, leading to the spinner remaining visible.

If you swallow your HTTP error in a `catchError', things will work as expected. Errors handling in a reactive stream in something a little bit touchy.

**Comment by sjpatel** [comment]
thanks @mpalourdio that's now working fine :)
