### ISSUE TITLE
Build issue with angular 8  after  migration 6 to 8

### ISSUE THREAD

**Issue by usmansaleh** [mpalourdio/ng-http-loader#133]
## Expected behavior
on ng serve below error
here are installed packages
{
  "name": "myApp",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@cloudinary/angular-5.x": "^1.0.2",
    "@ngx-progressbar/core": "^5.0.1",
    "@ngx-progressbar/http": "^5.0.1",
    "@ngx-progressbar/router": "^5.0.1",
    "@ngxs/devtools-plugin": "^3.0.1",
    "@ngxs/form-plugin": "^3.1.1",
    "@ngxs/router-plugin": "^3.0.1",
    "@ngxs/store": "^3.1.0",
    "bootstrap": "^4.3.1",
    "cloudinary-core": "^2.5.0",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "moment": "^2.22.1",
    "ng-http-loader": "^7.0.0",
    "ng2-scroll-to-el": "^1.2.1",
    "ngsm": "0.0.9",
    "ngx-bootstrap": "^5.0.0",
    "ngx-device-detector": "^1.3.5",
    "ngx-pagination": "^5.0.0",
    "ngx-print": "^1.2.0-beta.3",
    "ngx-quill": "^7.3.2",
    "ngx-toastr": "^8.6.0",
    "npm": "^6.5.0",
    "popper.js": "^1.15.0",
    "quill": "^1.3.6",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.5.4",
    "save": "^2.3.2",
    "sweetalert2": "^7.25.0",
    "time-ago-pipe": "^1.3.2",
    "tooltip.js": "^1.3.2",
    "tslib": "^1.10.0",
    "webdriver-manager": "^12.1.7",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.20",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.3",
    "node-sass": "^4.13.1",
    "ts-node": "~7.0.0",
    "tslint": "~5.9.1",
    "typescript": "~3.5.3"
  }
}

## Actual behavior

ERROR in ../node_modules/ng-http-loader/lib/services/pending-requests-interceptor.service.d.ts:11:9 - error TS1086: An accessor cannot be declared in an ambient context.

11     get pendingRequestsStatus$(): Observable<boolean>;
           ~~~~~~~~~~~~~~~~~~~~~~
../node_modules/ng-http-loader/lib/services/pending-requests-interceptor.service.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.

12     get pendingRequests(): number;
           ~~~~~~~~~~~~~~~
../node_modules/ng-http-loader/lib/services/pending-requests-interceptor.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get filteredUrlPatterns(): RegExp[];
           ~~~~~~~~~~~~~~~~~~~
../node_modules/ng-http-loader/lib/services/pending-requests-interceptor.service.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     set filteredMethods(httpMethods: string[]);
           ~~~~~~~~~~~~~~~
../node_modules/ng-http-loader/lib/services/pending-requests-interceptor.service.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     set filteredHeaders(value: string[]);
           ~~~~~~~~~~~~~~~
../node_modules/ng-http-loader/lib/services/pending-requests-interceptor.service.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     set forceByPass(value: boolean);
           ~~~~~~~~~~~
../node_modules/ng-http-loader/lib/services/spinner-visibility.service.d.ts:7:9 - error TS1086: mAn accessor cannot be declared in an ambient context.

7     get visibility$(): Observable<boolean>;

## Steps to reproduce

1. Just migrate my app from angular version 6 to 8.
2. and now I am facing this build time error

## ng-http-loader version
 "ng-http-loader": "^7.0.0",
## It does not work as expected on Internet explorer or Safari

Nothing works as expected on Internet explorer or Safari.

**Comment by mpalourdio** [comment]
`"ng-http-loader": "^7.0.0"` is comptable with `angular 9`

You must use `"ng-http-loader": "^6.0.0" with angular8. See the compatibility table in the README.

**Comment by usmansaleh** [comment]
> `"ng-http-loader": "^7.0.0"` is compatible with `angular 9`
> 
> You must use `"ng-http-loader": "^6.0.0"` with `angular 8`. See the compatibility table in the README. 

Sorry, my bad.
