### ISSUE TITLE
How can i use filter on method and filter on url in one request?

### ISSUE THREAD

**Issue by AZchVVT** [mpalourdio/ng-http-loader#134]

**Comment by mpalourdio** [comment]
Use both `filteredUrlPatterns` and `filteredMethods`

**Comment by AZchVVT** [comment]
i use but they work as OR

**Comment by mpalourdio** [comment]
Yes they are : https://github.com/mpalourdio/ng-http-loader/blob/b4955741a79ba0a41fad2e89d07e7389ba5437c2/src/lib/services/pending-requests-interceptor.service.ts#L69

**Comment by AZchVVT** [comment]
i see they use ||, but i need && :)

**Comment by AZchVVT** [comment]
can i set this filters not in html component?

**Comment by Halfist** [comment]
Is it possible to have spinner for **all** requests **but** PUT /path/to/certain-service?

Please note that POST /path/to/certain-service **should** have a spinner.

**Comment by Halfist** [comment]
@mpalourdio, is it possible to have spinner for **all** requests **but** PUT /path/to/certain-service?

Please note that POST /path/to/certain-service **should** have a spinner.

**Comment by mpalourdio** [comment]
@Halfist nope, not possible

**Comment by Halfist** [comment]
Thanks. Switched to using custom HTTP header for that purpose.
