### ISSUE TITLE
backdrop shows but spinner icon doesn't

### ISSUE THREAD

**Issue by EduardoIbarra** [mpalourdio/ng-http-loader#14]
Hello, recently I cloned my project on another computer, ran npm install and the spinner icon stopped showing. Backdrop shows ok and everything else is working fine. Is there any known bug related to a specific version causing this? 

Thanks!

**Comment by mpalourdio** [comment]
Not that I am aware of, sorry. Any code for reproduction ?

**Comment by Tiska** [comment]
same bug, happened when migrating from 0.2

**Comment by mpalourdio** [comment]
v0.3.1 introduced flexbox positioning. Can you try sticking to v0.3.0 and give me feedback ?

We use it in evergreen browsers here, without any issue AFAIK.

**Comment by Tiska** [comment]
seems to be just a color bug, i passed on 0.3.3 + a background color [backgroundColor]="'#ff0000'" and it works :) thanks

**Comment by mpalourdio** [comment]
Hey, just could reproduce without setting any backgroundColor. I should give one by default ! Wiil do this in v0.3.4

**Comment by mpalourdio** [comment]
In fact, this issue spotted a regression, as before I split all spinkit components in subcomponents, a default color was given by css.

I will get a fix very soon. Thanks for feeback !

**Comment by mpalourdio** [comment]
Just fixed this little nasty regression, will release a bugfix version later afternoon.

**Comment by mpalourdio** [comment]
@EduardoIbarra @Tiska , just released v0.3.4 that addresses this specific issue
