### ISSUE TITLE
Spinner doesn't work and Spinkit class not found

### ISSUE THREAD

**Issue by Wanted92** [mpalourdio/ng-http-loader#15]
Hi,

I followed your guide, so I imported Module and I put code `<spinner [spinner]="Spinkit.skWave"></spinner>` in my app.component.html

So, Spinkit class was not found.
Indeed if i write `<spinner></spinner>`, spinner doesn't work during an http request

System info:
angular: ^4.3.1

**Comment by mpalourdio** [comment]
Hi,

1. Obviously, `Spinkit` has to be referenced in your typescript class. See https://github.com/mpalourdio/ng-http-loader/issues/13

2. http requests **MUST** be performed with the "new" http api. Is it the case ?

Hard to tell what's wrong from your side without seeing code.

**Comment by alexnoise79** [comment]
Hi, 

i think you need to provide a bit more of Documentation, i'm sure the plugin is working well, but you cannot expect that every developer knows what you know :)

Thanks

**Comment by mpalourdio** [comment]
Hello,

Point 1 definitely needs to be documented. Point 2 *IS* documented. It's not perfect for sure, and any idea on how to improve doc is welcome.

**Comment by mpalourdio** [comment]
I've just added a little more documentation for those 2 points 

1. https://github.com/mpalourdio/ng-http-loader#customizing-the-spinner
2. https://github.com/mpalourdio/ng-http-loader#requirements

**Comment by mpalourdio** [comment]
Closing as lack of feedback. Feel free to re-open if needed
