### ISSUE TITLE
How know if loader is currently show?

### ISSUE THREAD

**Issue by kevin-schmitt** [mpalourdio/ng-http-loader#161]
## Expected behavior
Want to know if http loader currently display beacause have http request pending
## Actual behavior
I just found hide and show no function give this information
## ng-http-loader version
9
## It does not work as expected on Internet explorer or Safari

Nothing works as expected on Internet explorer or Safari.

Thanks

**Comment by mpalourdio** [comment]
You can surbscrige to the interceptor, like [this](https://github.com/mpalourdio/SpringBootAngularHTML5/blob/fcc97baa8cb7de29345564daffb2d8a377c55cfa/front/src/app/app.component.ts#L27-L32).

Closing as not an issue
