### ISSUE TITLE
MatSpinner not showing after Angular Update 13.2.6

### ISSUE THREAD

**Issue by Arghh** [mpalourdio/ng-http-loader#169]
## Expected behavior
MatSpinner animation is shown as own Spinner

## Actual behavior
Ng-Http-Loader is working and the Browser is blocked, while an http-request is running so ng-http-loader works fine. The Spinner is not shown. When I change the [entryComponent]="matSpinner" to [spinner]="spinkit.skWave" the Spinner is shown. So it is a Problem with [entryComponent] or the  { MatSpinner } from '@angular/material/progress-spinner'; 

## Steps to reproduce
After updating from Angular 13.2.0 to 13.2.6 the MatSpinner is not been shown.
I add <ng-http-loader [entryComponent]="matSpinner"></ng-http-loader> and in my Component I have MatSpinner defined as matSpinner = MatSpinner; from import { MatSpinner } from '@angular/material/progress-spinner'; 

It works fine with Angular VErsion (Material Version also 13.2.0) 13.2.0, but after the Update to 13.2.6 Angular/Material the Spinner https://material.angular.io/components/progress-spinner/overview is not been showing after the update.

## ng-http-loader version
11.0.1

**Comment by Arghh** [comment]
I tried angular 13.3.0 same result.
I did managed to get it working creating an extra component. "custom-spinner.component.ts" (empty) and template custom-spinner.component.html with just "<mat-spinner></mat-spinner>" tag. 

and changed [entryComponent]="matSpinner" to [entryComponent]="customSpinnerComponent" 
so I needed an extra template with mat-spinner html-tag and can't call matSpinner from import { MatSpinner } from '@angular/material/progress-spinner direkt in ng-http-loader tag.

I'm ok with this workaround and you can close the issue.

**Comment by mpalourdio** [comment]
Thanks for feedback.Closing now.
