### ISSUE TITLE
displaying spinner on individual components

### ISSUE THREAD

**Issue by Smon5** [mpalourdio/ng-http-loader#17]
is it possible to display spinner on specific components rather than in app component?

**Comment by mpalourdio** [comment]
What do you mean ? You can of course declare the ``<spinner></spinner>`` wherever you want.

**Comment by Smon5** [comment]
I am trying to access the spinner, and get the attached error. 
![capture](https://user-images.githubusercontent.com/26861687/31745571-dc30aa86-b4bf-11e7-86cd-acaf716be5b5.PNG)

**Comment by mpalourdio** [comment]
I have jsut tried to integrate the spinner to a sub-component without any error

``<spinner backgroundColor="#273c46" spinner="sk-wave"></spinner>
``

Does this work for you when the component is included in you main ``app.component`` ?

**Comment by Smon5** [comment]
Yes it works if included in app component.
I just tried to include NgHttpLoaderModule  in shared module and exported the same  and only then it worked. But i think, if a module is imported in app module it should be accessible across other modules as well?
I am still not able to achieve the desired result of displaying this spinner on specific section/component of a page.
Appreciate your help.

**Comment by mpalourdio** [comment]
The main spinner is full size, and tightly coupled with the interceptor. So even if you want to display multiple spinners on a same page, they will ALL react to ALL http requests.

You can implement your own interceptors and use individual components by implementing your own logic https://github.com/mpalourdio/ng-http-loader/blob/076429f8b5778f747effda8982d4d279c2ae58e2/src/app/spinkits.ts#L31-L39

**Comment by Smon5** [comment]
alright, thank you for your reply.
