### ISSUE TITLE
Use custom spinner

### ISSUE THREAD

**Issue by fzucaro** [mpalourdio/ng-http-loader#172]
## Expected behavior
Use a custom component as spinner
## Actual behavior
View custom componet as spinner but is showned standard spinner
## Steps to reproduce
https://stackblitz.com/edit/angular-ivy-k6etcr?file=src/app/app.module.ts
## ng-http-loader version
ver. 11 with angular 13

**Comment by mpalourdio** [comment]
Your code is wrong you should
 - Remove completely the `entryComponents` from your main `@NgModule`
 - Modify your `appComponent` to assign the component class to `MySpinner` field. ie. `public mySpinner = MySpinnerComponent;`
 - Enjoy
 
I have tested on your sample, it works as expected. I am going to modify the README.

**Comment by mpalourdio** [comment]
README and gists updated

**Comment by fzucaro** [comment]
It works fine. Thanks a lot !
