### ISSUE TITLE
Not working when I use "yarn install". Works using npm install

### ISSUE THREAD

**Issue by thienedits** [mpalourdio/ng-http-loader#18]
The spinner shows but then never disappears. The http.get() is never called.
package.json
````
{
  "name": "test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.5",
    "@angular/common": "^4.4.5",
    "@angular/compiler": "^4.4.5",
    "@angular/core": "^4.4.5",
    "@angular/forms": "^4.4.5",
    "@angular/http": "^4.4.5",
    "@angular/platform-browser": "^4.4.5",
    "@angular/platform-browser-dynamic": "^4.4.5",
    "@angular/platform-server": "^4.4.5",
    "@angular/router": "^4.4.5",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.5",
    "core-js": "2.4.1",
    "ng-http-loader": "^0.3.4",
    "ngx-swiper-wrapper": "4.6.2",
    "rxjs": "5.4.2",
    "zone.js": "0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.2",
    "@angular/compiler-cli": "^4.4.5",
    "@angular/language-service": "4.2.4",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "2.0.2",
    "@types/node": "6.0.60",
    "codelyzer": "3.1.1",
    "jasmine-core": "2.6.2",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.2.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "3.2.0",
    "tslint": "5.3.2",
    "typescript": "^2.5.3"
  }
}
````

**Comment by mpalourdio** [comment]
npm or yarn does not make ANY difference. What does ``The http.get() is never called`` mean ?

**Comment by thienedits** [comment]
I have an http.get() call in my code. When I clear my node_modules folder and then ran yarn install, the loader appears and shows the animation but then never disappears. I look in the dev tools network tab and see that no xhr request is ever made. I do the same thing except this time i run npm install. It works as should and i see the xhr request. 

With the yarn install, I tested and removed NgHttpLoaderModule from the imports in my app.module.ts and the xhr called as normal. Not sure where to look.  It may be a yarn issue? when I ran yarn install, I noticed yarn installed the wrong version of typescript so not sure if it's installing other wrong version of other packages. 

https://github.com/yarnpkg/yarn/issues/2154

**Comment by mpalourdio** [comment]
Thanks for feedback. I've just tried on a very fresh application, running yarn install, performing an http request and all seems ok at first sight. Will try to give it another try later.

Could you please replace your ``"typescript": "^2.5.3"`` by ``"typescript": "~2.3.3"`` in your dev-dependencies ?

**Comment by thienedits** [comment]
Yes i did that but then when i checked in node_modules folder after doing yarn install, typescript version showed 2.5.3

**Comment by mpalourdio** [comment]
And if you really stick to 2.3.3 ? ``"typescript": "2.3.3"``

**Comment by mpalourdio** [comment]
I've just  done a quick test :

``rm -rf node_modules && rm yarn.lock && yarn``

The typescript installed version is ``2.3.4``

**Comment by mpalourdio** [comment]
Another quick test, I have change typescript to ``"typescript": "^2.5.3"``

rm -rf node_modules && rm yarn.lock && yarn

The typescript installed version is 2.5.3, and no problem with the spinner in a "real" application.

**Comment by mpalourdio** [comment]
BTW, @angular-cli shows me this warning

> angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.5.3 was found instead.
> Using this version can result in undefined behaviour and difficult to debug problems.
> 
> Please run the following command to install a compatible version of TypeScript.
> 
>     npm install typescript@'>=2.1.0 <2.4.0'
> 
> To disable this warning run "ng set warnings.typescriptMismatch=false".

**Comment by thienedits** [comment]
Ok yea i got typescript 2.3.4 to install with yarn. However, the same thing happens. The loader just spins forever and never does an xhr request. Maybe It's because i have no root path define in my routes. In my routes i have no setting for the root path {path: ''}.
````
const routes: Routes = [
    {path: 'instore', component: InstoreComponent},
    {path: 'athome', component: AthomeComponent},
];
````
 In the main app.component.ts constructor I load a geolocation class. Inside the geolocation.ts contructor I call the http.get() and then on success i route using router.navigate to one of my paths. Its weird that doing npm install, it works fine.

**Comment by mpalourdio** [comment]
Well sorry but I cannot help you more. If the spinner shows, it really means that an http request is performed somewhere. :/

**Comment by mpalourdio** [comment]
https://github.com/angular/angular-cli/pull/8185

Hopefully when this released, things will work again for you. I experiences weird things those last days with latest ng-cli & typescript versions >=2.4

**Comment by thienedits** [comment]
I think I may have figured it out. I think I was using VSCode on windows and not running as Administrator. Then in the terminal window of vscode I was running "yarn install". After I ran as vscode as adminstrator, removed node_modules, ran yarn install. I think that fixed it. I also updated zone.js to 0.8.4, not sure if that did anything.
