### ISSUE TITLE
Class 'PendingInterceptorService' incorrectly implements interface 'HttpInterceptor' when running ng serve --prod

### ISSUE THREAD

**Issue by navrudh** [mpalourdio/ng-http-loader#19]
Attempting to AOT compile and run command `yarn ng serve --prod`

`ERROR in {application-path}/node_modules/ng-http-loader/pending-interceptor.service.d.ts (7,22): Class 'PendingInterceptorService' incorrectly implements interface 'HttpInterceptor'.
  Types of property 'intercept' are incompatible.
    Type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>' is not assignable to type '(req: HttpRequest<any>, next: HttpHandler) => Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
      Type 'Observable<HttpEvent<any>>' is not assignable to type 'Observable<HttpEvent<any>>'. Two different types with this name exist, but they are unrelated.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.`

Also note this problem does not occur when running `yarn ng serve --environment=prod` therefore I believe it could be an issue when AOT is enabled

**Comment by mpalourdio** [comment]
I've just tried on a fresh project, and I can't reproduce. Which angular-cli version are you using please ?

**Comment by navrudh** [comment]
angular/cli@1.4.9 

Also, versions of problematic classes
rxjs@5.5.1 @angular/common@4.4.6

**Comment by mpalourdio** [comment]
Can you try with ``"@angular/cli": "1.2.7"`` in you dev-dependencies ?

**Comment by navrudh** [comment]
Changed it and got the same error

**Comment by mpalourdio** [comment]
any project I could test ? Or at least can you gist your package.json ?

**Comment by mpalourdio** [comment]
Also, have you got some modules used with symlinks/npm link ?

**Comment by navrudh** [comment]
I ran npm-list-linked from my project directory and it returned nothing

**Comment by navrudh** [comment]
Gist of package.json https://gist.github.com/navrudh/774f8ab0f8fbed84b757430cb700974b

**Comment by mpalourdio** [comment]
- ng-http-loader is NOT in your package.json
- after adding it, I could reproduce your issue with your dependencies

The problem here seems that you have forced rxjs to 5.5.1. So to fix, use ``"rxjs": "^5.5.1"`` (notice the caret here)

**Comment by navrudh** [comment]
ng-http-loader: https://gist.github.com/navrudh/774f8ab0f8fbed84b757430cb700974b#file-package-json-L49

**Comment by mpalourdio** [comment]
wierd, I hadn't seen it... Is it ok for you now with rx ^5.5.1 ?

**Comment by navrudh** [comment]
No. I've changed rxjs to ^5.5.1 and the problem persists.

**Comment by mpalourdio** [comment]
did you yarn upgrade ?

**Comment by mpalourdio** [comment]
Also, what is the output of ``npm list rxjs``

**Comment by navrudh** [comment]
I didn't yarn upgrade. Did yarn install

**Comment by navrudh** [comment]
`npm list rxjs`:

```
+-- @angular/cli@1.4.9
| +-- @angular-devkit/schematics@0.0.34
| | `-- rxjs@5.4.3
| `-- rxjs@5.4.3
+-- ng-http-loader@0.3.4
| `-- rxjs@5.4.3
`-- rxjs@5.5.2
```

**Comment by mpalourdio** [comment]
Well, you should really remove completly your node_modules, and your yarn lock and re-run yarn.

After that, please post the output of ``npm list rxjs``

**Comment by navrudh** [comment]
I ran `yarn-upgrade` and build was successful

```
+-- @angular/cli@1.4.9
| +-- @angular-devkit/schematics@0.0.34
| | `-- rxjs@5.5.2  deduped
| `-- rxjs@5.5.2  deduped
+-- ng-http-loader@0.3.4
| `-- rxjs@5.5.2  deduped
`-- rxjs@5.5.2
```

**Comment by mpalourdio** [comment]
\o

**Comment by windmaomao** [comment]
I think this bug has something to do with putting another set of `node_modules` under a module (either under node_modules or in your app). What I did to solve this problem, delete all `@angular` dependencies inside the child module. 

It seems to me if package.json is detected, `node_modules` folder inside will be used against the root level `node_modules`.
