### ISSUE TITLE
[Enhancement] Separate Service Providers & Component Declarations into Two Modules

### ISSUE THREAD

**Issue by KeithGillette** [mpalourdio/ng-http-loader#20]
Thanks for making this nifty loading indicator available!

**Enhancement**
To facilitate [creating customized network activity components](https://github.com/mpalourdio/ng-http-loader/issues/6#issuecomment-325095049) to be displayed inside components loaded in modules other than `AppModule`, it would be useful to have the `PendingInterceptorServiceExistingProvider` & `PendingInterceptorServiceFactoryProvider` in a separate module from `SPINKIT_COMPONENTS`.

Their bundling in a single module prevents use of the SpinKit components inside a component declared in a different module, since the `PendingInterceptiorService` must be imported in the root `AppComponent` to interact with `HttpClientModule` application-wide, but then it can't be imported in another module to make the SpinKit components available there.

**Use Case**
Instead of overlaid in the middle of the screen, I would like to display a network activity indicator using the included SpinKits in the upper right-hand corner inside another component in a (lazy-loaded) module. I realize I could [create my own interceptor](https://github.com/mpalourdio/ng-http-loader/issues/17#issuecomment-338139279), but have no need of custom logic and am simply wanting to embed the network activity display functionality inside an existing component, so am happy to use the provided service.

**Work Around**
**`app.module.ts`**
```
…
const PendingInterceptorServiceExistingProvider = {
    provide: HTTP_INTERCEPTORS,
    useExisting: PendingInterceptorService,
    multi: true
};

@NgModule({
    imports: [
        HttpClientModule,
    ],
    providers: [
        PendingInterceptorServiceExistingProvider,
        PendingInterceptorServiceFactoryProvider,
    ]
})
export class AppModule {
}
```
**`main.module.ts`**
```
…
@NgModule({
    declarations: [
        SPINKIT_COMPONENTS,
        MyCustomNetworkActivityComponent
    ],
})
export class MainModule {
}
```

**Comment by mpalourdio** [comment]
Hello, and thanks for this GREAT issue description. But there are things here I just don't understand.

> Their bundling in a single module prevents use of the SpinKit components inside a component declared in a different module, since the PendingInterceptorService must be imported in the root AppComponent to interact with HttpClientModule application-wide, but then it can't be imported in another module to make the SpinKit components available there.

Could you please explain this point please. I just can't figure what makes import impossible in a sub-module at the moment.

About what you suggest, how exactly would this module be structured (in a BC manner)

- One sub-module with the ``PendingInterceptorServiceExistingProvider & PendingInterceptorServiceFactoryProvider``
- One sub-module with the ``SPINKIT_COMPONENTS`` definitions
- One main module that import && exports those both sub-modules and the main ``SpinnerComponent``?

Thanks for feedback

**Comment by KeithGillette** [comment]
Thanks for the fast & engaged reply, @mpalourdio!

Here's another stab at explaining the issue:

1. If I import the current `NgHttpLoaderModule` in a child module instead of (or in addition to) the `AppModule` where the Angular `HttpClientModule` is imported for the application, then the injected version of `PendingInterceptorService` that I get in my custom _NetworkActivityComponent_ declared in a child Angular module is disconnected from the application's HTTP traffic and `PendingInterceptorService.hasPendingRequests` is never true. 

2. If I attempt to use any of the `SPINKIT_COMPONENTS` in my custom _NetworkActivityComponent_ declared in a child Angular module without importing `NgHttpLoaderModule` in that same child module, Angular will throw errors in the browser console that the components are unknown.

1 + 2 = Catch 22!

So yes, I was able to Work Around that Catch 22 with the method described which implies to me that if the project was structured as follows, I could meet my Use Case without it:

- One `NgHttpLoaderService` sub-module with the `PendingInterceptorServiceExistingProvider` & `PendingInterceptorServiceFactoryProvider` providers _and no declarations or exports_, to be imported in `AppModule`.
- One `NgHttpLoaderComponents` sub-module declaring & exporting the `SpinnerComponent` & `SPINKIT_COMPONENTS` _and no providers_ to be imported in whichever modules are going to have them embedded, which could just also be the `AppModule` for the default use case for which you've designed the `SpinnerComponent`.

I see no need for a 3rd module combining those two. The Usage instructions would just be updated to import the `NgHttpLoaderService` & `NgHttpLoaderComponents` modules into the appropriate application modules.

Out of curiosity, what does "in a BC manner" mean?

**Comment by mpalourdio** [comment]
Thanks for those explanations ! I understand much better now, I need to test it myself those days.

> Out of curiosity, what does "in a BC manner" mean?

I meant **B**ackward **C**ompatibile :)

> I see no need for a 3rd module combining those two. The Usage instructions would just be updated to import the NgHttpLoaderService & NgHttpLoaderComponents modules into the appropriate application modules.

If I am able to split this module in sub-modules as required, we really need a 3rd module combining them. For multiple reasons :
- I want this module to be very easy to integrate for very common use cases. The 'magic' here is what makes it 'cool' IMO
- I don't want to force existing users upgrading their code because I add a convenient feature for some edge cases, even if those are valid.
- Adding features means adding maintenance.

I will come back later to this issue if I can find something EASY to implement, and fully BC.

Thanks for details and suggestions.

**Comment by mpalourdio** [comment]
As a side note, ``SpinnerComponent``, even in a standalone module has to be aware of ``PendingInterceptorService`` because it's a [strong requirement](https://github.com/mpalourdio/ng-http-loader/blob/f8c1eb3265993b73e688f208fb177843deb502f7/src/app/spinner/spinner.component.ts#L32).

Importing it as standalone in a sub-module of an application, without importing the module that would contain the service providers in the main application module would immediately make things fail.

If this is implemented, we should be very careful with this point and catch this incoherence very soon to lead the developer.

**Comment by mpalourdio** [comment]
I've just tried a first implementation of modules splitting and it seems to work quite well. Some things are broken, like paths for services, but it's acceptable I thing, as it was not really meant to be public API at first sight, and we did not reach v1.0 for the moment, so we are a *little* more relax regarding semver.

**Comment by mpalourdio** [comment]
Code has been decomposed this way :
- a new NgHttpLoaderServicesModule that can be used standalone
- a new NgHttpLoaderComponentsModule that can be used standalone (but needs NgHttpLoaderServicesModule)
- The main and yet existing  NgHttpLoaderModule thant imports and export the 2 new modules

**Comment by KeithGillette** [comment]
Thanks for your quick action on this idea, @mpalourdio. The changes looks fine upon inspection. I tried to pull the referenced commit to test but for some unknown reason keep getting an error:

```
ng-http-loader@0.3.4  invalid (git://github.com/mpalourdio/ng-http-loader.git#8ae0a9f37d326f9f532de90df1d68dfd9b1583b6
```

**Comment by mpalourdio** [comment]
Now that angular 5 is out, I will give this a shot next week.

**Comment by mpalourdio** [comment]
Version 0.5.0 has just been released
