### ISSUE TITLE
Error ng build

### ISSUE THREAD

**Issue by EloyCs1** [mpalourdio/ng-http-loader#21]
I have an error when I use ng build:

ERROR in Error: Metadata version mismatch for module C:/Users/......../angular/node_modules/ng-http-loader/ng-http-loader
.module.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/......./angular/src/app/app.module.ts

This is my packaje.json:

`{
  "name": "angular",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",
    "@angular/router": "^4.4.6",
    "angular2-datatable": "^0.6.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ng-http-loader": "^0.4.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.3",
    "@angular/compiler-cli": "^4.4.6",
    "@angular/language-service": "^4.4.6",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.90",
    "angular2-datatable": "^0.6.0",
    "bootstrap": "^3.3.7",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}`

**Comment by mpalourdio** [comment]
Please post your package.json.
The last compatible version with angular 4.4.6 is v0.3.4.

If you want to use angular 5, use version 0.4.0

**Comment by EloyCs1** [comment]
Is working, thank you!!!!

**Comment by mpalourdio** [comment]
Good :)

I have just document this here : https://github.com/mpalourdio/ng-http-loader#angular-4--angular-5

Thanks for feedback!
