### ISSUE TITLE
Start and Stop Manually?

### ISSUE THREAD

**Issue by ViniciusReno** [mpalourdio/ng-http-loader#22]
Can I start and stop the spinner anytime?

**Comment by mpalourdio** [comment]
Not possible at the moment. The subject is not public https://github.com/mpalourdio/ng-http-loader/blob/25f9488b2c5bc882749ab5147e70f8eddfb418b4/src/app/pending-interceptor.service.ts#L22

I suppose this is something we could add, but I can't see the real use case

**Comment by mpalourdio** [comment]
Anyway, all the components are usable as standalone, so you can implement your own show/hide logic on them.

**Comment by mpalourdio** [comment]
Closing as not an issue. Feel free to re-open if needed.

**Comment by bdsoko** [comment]
I have a unique requirement where I could use this feature - manually controlling start/stop of the spinner.  My Angular 5 application makes use of the "HttpClientModule" as well as a jquery library which makes ajax calls.  I'd like to be able to use this library to hide/show the spinner while this jquery library is performing its tasks.  Any suggestions on how I can best go about that?

**Comment by mpalourdio** [comment]
I have no idea how to trig things from the jquery side. You should go with a manual show/hide at Jquery side. This module targets angular only.

**Comment by mpalourdio** [comment]
See https://github.com/mpalourdio/ng-http-loader/issues/53
