### ISSUE TITLE
Error when install and serve 

### ISSUE THREAD

**Issue by claudioc8211** [mpalourdio/ng-http-loader#3]
I've made a new project only for test this http-loader; i've followed the instruction and when serve the app i've this issue below : 
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in D:/learning/Angular/spinner-test/node_modules/ng-http-loader/node_modules/@angular/core/core.d.ts, resolving symbol NgHttpLoaderModule in D:/learning/Angular/spinner-test/node_modules/ng-http-loader/ng-http-loader.module.d.ts, resolving symbol NgHttpLoaderModule in D:/learning/Angular/spinner-test/node_modules/ng-http-loader/ng-http-loader.module.d.ts

ERROR in ./~/ng-http-loader/ng-http-loader.module.js
Module not found: Error: Can't resolve '@angular/common/http' in 'D:\learning\Angular\spinner-test\node_modules\ng-http-loader'
 @ ./~/ng-http-loader/ng-http-loader.module.js 15:13-44
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

where is my fault ?

**Comment by mpalourdio** [comment]
The error you see is not in this module IMO. Without seeing code, it's hard to tell what is happening.

Please not that this module is only compatible with angular 4.3+

**Comment by claudioc8211** [comment]
When angular-cli create a new project it sets Angular from 4.0.0 version. I've changed it's version and all is ok.
Thank you

**Comment by mpalourdio** [comment]
Thanks for feedback !
