### ISSUE TITLE
Unable to customise spinner

### ISSUE THREAD

**Issue by Tora-Bora** [mpalourdio/ng-http-loader#31]
I should use my own spinner. It would be great if i could create my own component like SkWanderingCubesComponent and set it to spinner , but you hardcoded component names in spinner.component.html. May be it would be better to use ng_content inside spinner component?

**Comment by mpalourdio** [comment]
That's definitely something I'm planning in the near future.

**Comment by zapbr** [comment]
did you have any predictions for this feature?

**Comment by mpalourdio** [comment]
No ETA at the moment. I wish this feature could land in master by the end of January but I miss time :(

**Comment by zapbr** [comment]
I was thinking.
If you put a new property 'customHTML' and 'customStyle' that, if exists, replaces the 'template' and 'styles' on decorator?
I think it is a simple solution but very very powerful.

**Comment by mpalourdio** [comment]
Is it even possible ? Any resource with this trick somewhere ?

**Comment by zapbr** [comment]
I think it is possible
I will try todo this on my local environment and send you the code.

Em 12 de jan de 2018 18:18, "Michel Palourdio" <notifications@github.com>
escreveu:

**Comment by zapbr** [comment]
I tested and this worked very well.

On 'SpinnerComponent.propDecorators': 
```javascript
"customTemplate": [{ type: core_1.Input },],
```

On 'SpinnerComponent.decorators' changed the template attribute:
```javascript
template: "<div *ngIf=\"isSpinnerVisible && customTemplate\" [innerHTML]=\"customTemplate\" ></div><div id=\"spinner\" *ngIf=\"isSpinnerVisible && !customTemplate\" ><sk-cube-grid *ngIf=\"spinner === Spinkit.skCubeGrid\" [backgroundColor]=\"backgroundColor\"></sk-cube-grid><sk-chasing-dots *ngIf=\"spinner === Spinkit.skChasingDots\" [backgroundColor]=\"backgroundColor\"></sk-chasing-dots><sk-double-bounce *ngIf=\"spinner === Spinkit.skDoubleBounce\" [backgroundColor]=\"backgroundColor\"></sk-double-bounce><sk-rotating-plane *ngIf=\"spinner === Spinkit.skRotatingPlane\" [backgroundColor]=\"backgroundColor\"></sk-rotating-plane><sk-spinner-pulse *ngIf=\"spinner === Spinkit.skSpinnerPulse\" [backgroundColor]=\"backgroundColor\"></sk-spinner-pulse><sk-three-bounce *ngIf=\"spinner === Spinkit.skThreeBounce\" [backgroundColor]=\"backgroundColor\"></sk-three-bounce><sk-wandering-cubes *ngIf=\"spinner === Spinkit.skWanderingCubes\" [backgroundColor]=\"backgroundColor\"></sk-wandering-cubes><sk-wave *ngIf=\"spinner === Spinkit.skWave\" [backgroundColor]=\"backgroundColor\"></sk-wave></div>",
```

On my HTML i simple put 
```html
<spinner customTemplate='<img src="http://www.linkinads.com/images/loading-blue.gif" alt="loader">' ></spinner>
```

I trying to figure out how to do the same with the styles ... but, if you put the styles on the project SCSS work fine.

**Comment by mpalourdio** [comment]
Thanks for trying. I was more thinking of giving directly an html file, that could be evaluated/compiled.
Something life ``file_get_contents`` in ``php``

[NgComponentOutlet](https://angular.io/api/common/NgComponentOutlet) could do the job.

**Comment by mpalourdio** [comment]
Pseudo code could be cool

``html
<spinner [htmlTemplate]="'path/to/file.html'" [cssTemplate]="'path/to.css'"></spinner>
``

**Comment by zapbr** [comment]
Hummm
Looks a better solution and very elegant way.
In other components they have everything on config files.
But in this way is more flexible.
I like it.


Em 12 de jan de 2018 19:34, "Michel Palourdio" <notifications@github.com>
escreveu:

**Comment by mpalourdio** [comment]
It appears that I can't hack someting acceptable with this idea. But, ``ngComponentOutlet`` pretty does the job, And i find it cleaner than a single ``<ng-content>``.

@Tora-Bora , @zapbr, what do you think about linking a full component rather than adding content between ``<spinner>`` tags ?

**Comment by zapbr** [comment]
Totally agree
The current solution is nice, but a full component is way more powerful and customisable.
Sounds like a new milestone

**Comment by mpalourdio** [comment]
Code and tests for this feature has landed into master. It needs documentation before releasing.

**Comment by mpalourdio** [comment]
Documentation here : https://github.com/mpalourdio/ng-http-loader/blob/0.7.0/README.MD#defining-your-own-spinner with you want to give it a read before the release.

**Comment by mpalourdio** [comment]
Version 0.7.0, containing this feature has just been published. Thanks all for your feedback \o
