### ISSUE TITLE
Manually Handle Loader

### ISSUE THREAD

**Issue by harshadray** [mpalourdio/ng-http-loader#33]
It has been great library to work with HTTPClient Module, but it works only when HTTPClient used internally.
I'm using [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) which manage http internally hence it is not showing any loader while making request.

Is there any way I can show loader manually using code?

**Comment by mpalourdio** [comment]
Please see https://github.com/mpalourdio/ng-http-loader/issues/22 to trigger things manually. But of a third module does not use HttpClientModule, or does not provide any event you can listen to, there's nothing you can do.

Closing as not an issue.

**Comment by mpalourdio** [comment]
See https://github.com/mpalourdio/ng-http-loader/issues/53
