### ISSUE TITLE
Integration with nProgress.js

### ISSUE THREAD

**Issue by VickNet** [mpalourdio/ng-http-loader#34]
Integrate ng-http-loader and [nProgress](https://github.com/rstacruz/nprogress).
Make slim progress bars like on YouTube, Medium, etc avaible in angular with realistic progress.

_Thank you, Michel Palourdio._

**Comment by mpalourdio** [comment]
Hello,

sorry for delay. I don't want to add 3rd party dependency ATM. But a look-alike loader could be very cool, but is really useful when you are able to calculate how long will your processing last, which is mostly impossible with http requests.
