### ISSUE TITLE
SystemJS Error loading ng-http-loader

### ISSUE THREAD

**Issue by mitmacher** [mpalourdio/ng-http-loader#35]
Hi,

I want to try out your spinners but I cant get it to work with SystemJS. I am getting this error:

> Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng-http-loader/ng-http-loader.module
> 	wrapFn@http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:30
> 	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:425:17
> 	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:192:28
> 	ZoneTask.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:499:24
> 	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:9
> 	globalZoneAwareCallback@http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17
> 	
> 	Error loading http://localhost:3000/ng-http-loader/ng-http-loader.module as "ng-http-loader/ng-http-loader.module" from http://localhost:3000/app/app.module.js
> Stack trace:
> (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng-http-loader/ng-http-loader.module
> 	wrapFn@http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:30
> 	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:425:17
> 	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:192:28
> 	ZoneTask.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:499:24
> 	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:9
> 	globalZoneAwareCallback@http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17
> 	
> 	Error loading http://localhost:3000/ng-http-loader/ng-http-loader.module as "ng-http-loader/ng-http-loader.module" from http://localhost:3000/app/app.module.js

I kow that he can't find the module and that I have to write the reference to systemjs.config but I tried pretty much everything and it was never able to find the module. 

Do you have any hints for me here?

Thanks in advance.

**Comment by mpalourdio** [comment]
Hello,

the compilation process targets ``commonjs`` https://github.com/mpalourdio/ng-http-loader/blob/bfe0af9155ef160f26f7ae8802688a3169d9ff6a/tsconfig.ngc.json#L4

I don't know if that's the problem. I am not experienced enough with systemJS to help you :( 

Did you get the module with npm or did you clone from github ?

**Comment by mpalourdio** [comment]
Closing as no feedback. Feel free to re-open if needed

**Comment by mpalourdio** [comment]
V2.0.x will likely be compatible with SystemJS, as the module will be packaged
