### ISSUE TITLE
Loading text with spinner

### ISSUE THREAD

**Issue by kshkrao3** [mpalourdio/ng-http-loader#36]
Is there any way to add dynamic loading text changing with each request? I don't find it documented anywhere.

**Comment by mpalourdio** [comment]
Hello,

This feature does not exist.

**Comment by kshkrao3** [comment]
@mpalourdio Can this be a feature request?

**Comment by mpalourdio** [comment]
I don't really see how we could add a different ssage ``per`` http request. Adding a common text under the spinner could be easily done. Not sure if it's worth the job TBH.

**Comment by kshkrao3** [comment]
So with the common text concept, I would believe that we can have some shared variable holding its value and getting updated on each request. But yea, we cannot put it in one single place, as in HttpInterceptors and rather it has to be updated with each request. Well since I had very fewer HTTP requests [<10], I managed to define a global/shared variable and change its value and place it in a position absolute div. Thanks for the quick reply. :)
