### ISSUE TITLE
Add minimum loading time

### ISSUE THREAD

**Issue by ilianiv** [mpalourdio/ng-http-loader#37]
It will be nice if you could set a minimum spinning time. It's irritating when your API respond in 120ms for example and the spinner just flashes the screen.

**Comment by mpalourdio** [comment]
Taht's what ``debounceDelay`` is for :) Please see [options](https://github.com/mpalourdio/ng-http-loader/blob/master/README.MD#customizing-the-spinner)

**Comment by ilianiv** [comment]
If you set 100ms debounceDelay and your API respond in 150ms you will have 50ms of visible spinner. I think an option that will ensure visible spinner for some time will be useful. 

Example:
```
Debounce time: 100ms
Min spinning time: 300ms
---0ms--------100ms------------180ms-----------400ms--
----|----------|-----------------|---------------|-- 
req starts  spinner shows    req ends     spinner hides

**Comment by mpalourdio** [comment]
Yes, that could be really nice !

**Comment by mpalourdio** [comment]
See this PR : #73 

Feedbacks welcome, particularly on the name of the option which is ``minimumDuration`` for the moment.

**Comment by ilianiv** [comment]
You may call it just `minDuration`

**Comment by mpalourdio** [comment]
Done !

**Comment by mpalourdio** [comment]
Feature added in v2.1.0 !
