### ISSUE TITLE
Support material spinner

### ISSUE THREAD

**Issue by davidkarlsen** [mpalourdio/ng-http-loader#42]
It would be great to support ther material design spinner(s): https://material.angular.io/components/progress-spinner/overview

How to go about that?

**Comment by mpalourdio** [comment]
From version 0.7.0, you can define your own spinner : https://github.com/mpalourdio/ng-http-loader/blob/master/README.MD#defining-your-own-spinner

**Comment by davidkarlsen** [comment]
Hmm, it is not so easy for: https://material.angular.io/components/progress-spinner/overview (the components have a number of dependencies injected through ctor)

I tried following https://gist.github.com/mpalourdio/e05b4495de2abeeecfcf92d70e4ef93e - but it won't work. If the <spinner> could work as an *ngIf wrapping the actual spinner inside it would be very easy.

**Comment by mpalourdio** [comment]
Hello, I've just tried and it seems to work. Please see https://gist.github.com/mpalourdio/2c0bec03d610b24ff49db649fbb69a48

**Comment by davidkarlsen** [comment]
Certainly it does! I must have screwed up something or not being able to reload-properly. Sorry for the noise - closing

**Comment by mpalourdio** [comment]
Thanks for feedback, good to know !
