### ISSUE TITLE
I can't create my own Spinner.

### ISSUE THREAD

**Issue by dgribeiro** [mpalourdio/ng-http-loader#43]
Hi,

I follow your tutorial to create my own spinner, but doesn't work. The default spinner continued to appear. I don't know the right way to reference my component in app.component.ts. Can you show me a Example of how to implement this Feature?

Thank you so much!
Douglas

**Comment by mpalourdio** [comment]
Here you go : https://gist.github.com/mpalourdio/e05b4495de2abeeecfcf92d70e4ef93e

Take attention at ``AwesomeComponent`` in every three files

**Comment by dgribeiro** [comment]
It worked!!
Thank's a lot.

**Comment by mpalourdio** [comment]
\o . Closing now.
