### ISSUE TITLE
filteredUrlPatterns doesn't work

### ISSUE THREAD

**Issue by michaelyangzz** [mpalourdio/ng-http-loader#44]
my code 
<spinner [backgroundColor]="'#ff0000'"
         [spinner]="spinkit.skCubeGrid"
         [debounceDelay]="0"
         [filteredUrlPatterns]="['api']"></spinner>

my request url is http://localhost:59845/api/values/.
my package.json   "ng-http-loader": "^0.7.0",
but spinner shown for every request.  it shouldn't show because the url contains 'api' . did i misunderstand??

**Comment by mpalourdio** [comment]
Weird, need to test it myself on a project of mine. Any code of yours I can checkout to test ?

**Comment by michaelyangzz** [comment]
thank you very much, haha....    there is another request...at the same time.....

**Comment by mpalourdio** [comment]
Thanks for feedback. Closing as not an issue :)
