### ISSUE TITLE
Feature request: option to change foreground color.

### ISSUE THREAD

**Issue by ybrodsky** [mpalourdio/ng-http-loader#47]
Option to change the foreground color: that is, the color of the layer that covers the content / the spinner container.

> #spinner[_ngcontent-c0] {
>   background-color: THIS
> }

**Comment by mpalourdio** [comment]
You can easily do it at css level

`#spinner { background-color: #000 !important; }`

Not something I'm planning to add, as it's very trivial to add at application level.

**Comment by mpalourdio** [comment]
Closing as it will not be implemented in a near future.
