### ISSUE TITLE
How to enable from another component

### ISSUE THREAD

**Issue by surjit** [mpalourdio/ng-http-loader#49]
How can i show this from another component ?
I have below component, when onClick called, I want to show spinner
how can i achieve this, please advise
```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-server-services',
  templateUrl: './server-services.component.html',
  styleUrls: ['./server-services.component.scss']
})
export class ServerServicesComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }
 
 onClick(){
  this.isSpinnerVisible = true;
}

}
```

**Comment by mpalourdio** [comment]
Integrate the component you want to use and implement your own show/hide logic. This module targets http interceptors. If you just want to show/hide a material-design spinner on-click, you have to do the job yourself. That's not the purpose of this module, sorry.
