### ISSUE TITLE
Custom spinner usage

### ISSUE THREAD

**Issue by BKB503** [mpalourdio/ng-http-loader#5]
Hello, 

If any one using custom spinner rather than default. Need to import  Spinkit in app component and 

import{Spinkit } from 'ng-http-loader/spinkits';

decalare   public spinkit= Spinkit.skChasingDots;

<spinner [backgroundColor]="'#ff0000'"  [spinner]='spinkit'></spinner>

**Comment by mpalourdio** [comment]
Thanks for pointing this. Could be referenced in the README I suppose.
