### ISSUE TITLE
Not working for Lazy load modules

### ISSUE THREAD

**Issue by jeevasusej** [mpalourdio/ng-http-loader#51]
I have modules like ParentModule and ChildModule.

Child module has loaded lazily.

When I configure it, it works for the ParentModule service but not for ChildModule Services.
Do I need to configure again in the ChildModules?

**Comment by mpalourdio** [comment]
I have never ever used lazy module, sorry. What could be cool is a minimal project where I could easily reproduce the problem so I can give it a try

**Comment by jeevasusej** [comment]
Yes, I will try to give you the sample.

If I import the modules to child modules, then it is working. 
But I need to call the component again. 

We need a common one for the whole application.

**Comment by mpalourdio** [comment]
Sure, let me know when you're (very) minimal sample is ready, I'd like to give it a try

**Comment by jeevasusej** [comment]
This is not a bug.

For this need to export **HttpClientModule** from the main module.
Instead of instantiating in each child lazy loaded module, instantiate only on the Parent module.
**HttpClientModule**

**Comment by mpalourdio** [comment]
Oh I see, the interceptor. Thanks for the feedback, good to know !
