### ISSUE TITLE
How to call the loader explicitly 

### ISSUE THREAD

**Issue by Bsujeet** [mpalourdio/ng-http-loader#52]
Hi,
I want to call the loader explicitly for events like router navigation and others.
Do we have some functionality for it.

Thanks.

**Comment by mpalourdio** [comment]
That's not something easily doable. The ``SpinnerComponent`` contains a ``isSpinnerVisible`` property. If you can get an instance of ``isSpinnerVisible`` inside a class, you can explicitly change this parameter's value.

**Comment by mpalourdio** [comment]
I was looking at this, as it's something that comes in issues from time to time, and I think I should refactor a bit ``PendingInterceptorService`` so the ``pendingRequestsStatus()`` method does not return anymore an observable but the ``ReplaySubject<boolean>`` so we could handle the spinner visibility manually

**Comment by mpalourdio** [comment]
I have created an issue to track this feature : https://github.com/mpalourdio/ng-http-loader/issues/53

**Comment by mpalourdio** [comment]
Closing as not possible at the moment, and another issue has been created to track the progress of this new feature.

**Comment by mpalourdio** [comment]
@Bsujeet I've just release version 0.8.0 with this feature. See https://github.com/mpalourdio/ng-http-loader#manually-show-and-hide-the-spinner

**Comment by mpalourdio** [comment]
Releasing v0.9.0 with a more friendly API

**Comment by Bsujeet** [comment]
Thanks @mpalourdio , 
for resolving this issue.
