### ISSUE TITLE
Manually show/hide the spinner component

### ISSUE THREAD

**Issue by mpalourdio** [mpalourdio/ng-http-loader#53]
Sometimes, outside of http requests, it could be convenient to have the possibility to show/hide the spinner component.

We could add a new injectable service, ``SpinnerVisibilityService`` , that references a subject in which we could pipe true/false, to show or hide the spinner when needed.

**Comment by mpalourdio** [comment]
Would fix #22 #33 #52

**Comment by mpalourdio** [comment]
```typescript
import { SpinnerVisibilityService } from 'ng-http-loader/services/spinner-visibility.service';

@Component({
    selector: 'my-component',
    templateUrl: './my.component.html',
    styleUrls: ['./my.component.css'],
})
export class MyComponent {

    constructor(private visibilityService: SpinnerVisibilityService) {
        // show the spinner
        visibilityService.visibilitySubject.next(true);
        // hide the spinner
        visibilityService.visibilitySubject.next(false);
    }
}
```

**Comment by mpalourdio** [comment]
Handling the visibility with an observable is the way to go here, to avoid the famous ``ExpressionChangedAfterItHasBeenCheckedError``

**Comment by mpalourdio** [comment]
Fixed in v 0.8.0

**Comment by mpalourdio** [comment]
Version 0.9.0 provides a more friendly API

**Comment by matthewkooshad** [comment]
i'm  facing the ExpressionChangedAfterItHasBeenCheckedError when i try to use `this.spinnerVisibilityService.show();` in `ngOnInit` in a component. i'm trying to see how to handle it, and i came across this page.
