### ISSUE TITLE
Spinner sometimes visible when it shouldn't be

### ISSUE THREAD

**Issue by mset** [mpalourdio/ng-http-loader#58]
Hi, 
I have seen the spinner not disappearing after all requests have finished. I have gone through the code and noticed the following:

Some HTTP requests may be initiated by a process that runs outside the Angular zone (e.g. external oAuth authentication). As a consequence, such requests will cause the pendingRequestsStatus rx subject in PendingInterceptorService to fire also outside the Angular zone, leading to Angular change detection not kicking in and the spinner can stay visible even after all HTTP requests have finished.
Probably the best way around it is to emit on the subject explicitly inside the Zone.

Cheers,
Marek

**Comment by mpalourdio** [comment]
I would be glad to see a very small project that reproduces the issue, so we can troubleshoot what is really happening.

**Comment by mset** [comment]
I cannot share the project where the problem exists with you as it is not a public project, but it should not be too difficult to simulate it by running one of the http requests outside of the angular zone.

**Comment by mpalourdio** [comment]
Closing as lack of feedback and never been able to reproduce.
