### ISSUE TITLE
Can we extend to use more spinner types or custom css 

### ISSUE THREAD

**Issue by BKB503** [mpalourdio/ng-http-loader#6]
Hello, 

is it possible to extend to use any custom css and message?

Thanks

**Comment by mpalourdio** [comment]
Hello,

yes you can of course create your own component, and subscribe to the ``pendingRequestStatus`` observable to handle you own spinner and your own logic for show/hide

Have a look at https://github.com/mpalourdio/ng-http-loader/blob/94c2d02b90370056af358457b3e510f356c57d50/src/app/spinner/spinner.component.ts

**Comment by BKB503** [comment]
Ok Great Thanks

**Comment by mpalourdio** [comment]
Just di a quick test here : https://github.com/mpalourdio/SpringBootAngularHTML5/blob/019525b3d048a31cabd346e7df70cbf17824fdc5/front/src/app/app.component.ts#L23-L27 for reference
