### ISSUE TITLE
RxJS not tree shaked

### ISSUE THREAD

**Issue by ilianiv** [mpalourdio/ng-http-loader#68]
Hi, 
I've noticed that when I add ng-http-loader into my project the whole (or big part of) RxJS appears in main.bundle (using `ng bulid --prod`). Your RxJS imports look fine and I can't determine why this happens.

Here is an empty angular project made with
```
ng new test-prj
````

**Before**
RxJS modules before ng-http-loader ~17kB
![image](https://user-images.githubusercontent.com/3925630/40176815-535b7a44-59e5-11e8-9457-bd54b15d8674.png)

**After**
RxJS modules after ng-http-loader ~140kB
![image](https://user-images.githubusercontent.com/3925630/40176833-5f628bd4-59e5-11e8-91a6-ee7ae11f34a7.png)

Hope you will figure out the problem.

**Comment by mpalourdio** [comment]
Wow, thanks for reporting, that's bad :(

What is strange, it's that once transpiled and published, the module does not contain the full lib, taht for me the tree shake is ok. Can you please share your project so I can clone and test ?

**Comment by ilianiv** [comment]
It's just a newly generated app with angular cli + HttpClientModule + NgHttpLoaderModule:

https://github.com/ilianiv/ng-http-loader-rxjs-tree-shake-test

**Comment by ilianiv** [comment]
ng build —prod —source-maps

will generate source maps for you and then you can explore them with tool like 
https://www.npmjs.com/package/source-map-explorer

After a quick overview I didn’t manage to find the reason why so much rxjs modules get bundled.

Илиян Иванов
---
Iliyan Ivanov

**Comment by ilianiv** [comment]
Yep, looks better :)

Илиян Иванов
---
Iliyan Ivanov

**Comment by mpalourdio** [comment]
Fixed here : https://github.com/mpalourdio/ng-http-loader/commit/cbe41c6547b586291c647fdf4a2a8a7e2e708516

A new release will come later this afternoon. Thanks again for the report !

**Comment by mpalourdio** [comment]
Fixed in V 1.0.2.

Thanks for reporting this !

**Comment by ilianiv** [comment]
Thanks for the fix

Илиян Иванов
---
Iliyan Ivanov
