### ISSUE TITLE
Exclude some requests

### ISSUE THREAD

**Issue by baptistecosta** [mpalourdio/ng-http-loader#7]
Hi, is there a way to exclude some requests from triggering the loader?

**Comment by mpalourdio** [comment]
Hello, not at the moment. But I am curious to read a concrete use case and in which way you would exclude those requests.

The quick way I can see for such a feature, is the detection of a specific header in the requests you would like to exclude.

**Comment by baptistecosta** [comment]
I'm adding an autocomplete to a form which fetch remote data using HTTP client. Every time I type in some text, the loader appears and I would like to avoid this behavior.
This could be a header indeed but I was thinking of a list of URLs that could be exluded.

**Comment by mpalourdio** [comment]
I see. You could try to unsubscribe the `pendingRequestsStatus` during those specific requests.

The problem is, today, the subscriber instance is private https://github.com/mpalourdio/ng-http-loader/blob/94c2d02b90370056af358457b3e510f356c57d50/src/app/spinner/spinner.component.ts#L32

**Comment by mpalourdio** [comment]
A last fix, would be to simply hide the full loader in css. THe main div'is is ``http-loader`` 
https://github.com/mpalourdio/ng-http-loader/blob/94c2d02b90370056af358457b3e510f356c57d50/src/app/spinner/spinner.component.html#L1

**Comment by mpalourdio** [comment]
What I am thinking about, would be to add an ``excludedUrlPattern`` which would take a regexp to check before triggering. It's a little less user-friendly than an array of url to exclude but more powerful.

Another solution could be an ``excludeUrlStartingWith``, but I don't really like this solution.

What do you think ? Is the css trick with ``display: none`` not suitable ? Any other clue given below suitable ?

**Comment by baptistecosta** [comment]
The CSS trick is buggy and not pretty but it does the job. An array of URLs regex would be the best in my opinion.

**Comment by mpalourdio** [comment]
I agree, it's not pretty. I can go for an array of regex in a near future !

**Comment by mpalourdio** [comment]
Handled in https://github.com/mpalourdio/ng-http-loader/pull/9/files if you want to give it a first shot.

**Comment by mpalourdio** [comment]
Version 0.3.0 has just been published !
