### ISSUE TITLE
Error: Object(...) is not a function...

### ISSUE THREAD

**Issue by claudioviola** [mpalourdio/ng-http-loader#75]
Hi

I've been receiving this error message
![schermata 2018-06-05 alle 15 48 11](https://user-images.githubusercontent.com/6689594/40980079-e3abe9de-68d7-11e8-9e55-7d429750254a.png)

My Anuglar's configuration is like follow:
    "angular-redux/store": "^7.1.1",
    "angular/animations": "5.2.8",
    "angular/cdk": "5.2.4",
    "angular/common": "5.2.8",
    "angular/compiler": "5.2.8",
    "angular/core": "5.2.8",
    "angular/forms": "5.2.8",
    "ngular/http": "5.2.8",
    "angular/platform-browser": "5.2.8",
    "angular/platform-browser-dynamic": "5.2.8",
    "angular/router": "5.2.8",
    "ng-bootstrap/ng-bootstrap": "1.0.1",

I imported both: BrowserModule and HttpClientModule.
Any solution? It's strange...
Thank you!

**Comment by mpalourdio** [comment]
Version 1.x and 2.x are only compatible with angular 6.

**Comment by mpalourdio** [comment]
See https://github.com/mpalourdio/ng-http-loader#angular-4--angular-5--angular-6

**Comment by claudioviola** [comment]
😇 Swear! I read it! But didn't catch that. Sorry!

**Comment by mpalourdio** [comment]
No problem. Closing now as not an issue.
