### ISSUE TITLE
Requests filtering by HTTP header

### ISSUE THREAD

**Issue by wolfmarco** [mpalourdio/ng-http-loader#76]
We use conditional requests to refresh our Angular client data in the background. For this we use the same requests as for the foreground requests. The only differences are the additional HTTP Headers `If-Modified-Since` and `If-None-Match`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match

It would be great to have a HTTP header filter to avoid a spinner for the background requests.

Something like this:

<spinner [filteredHeaders]="['If-Modified-Since','If-None-Match']"></spinner>

**Comment by mpalourdio** [comment]
Now that we have url filtering, method filtering, I can consider adding this too.
Marking as feature request.

**Comment by mpalourdio** [comment]
WIP here : https://github.com/mpalourdio/ng-http-loader/tree/filtered_headers

Should be released in the next few days

**Comment by wolfmarco** [comment]
Solved faster than thought. Thanks for this!

**Comment by mpalourdio** [comment]
Feature landed in v2.3.0.
