### ISSUE TITLE
AOT compilation problem

### ISSUE THREAD

**Issue by EduardoIbarra** [mpalourdio/ng-http-loader#8]
I am working on an app using Angular 4.3.5.

When I run the ng build command on our QA server, I get this error:

> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/tornado-qa1/tornadobus/frontend/www-admin/node_modules/ng-http-loader/node_modules/@angular/core/core.d.ts, resolving symbol NgHttpLoaderModule in /home/tornado-qa1/tornadobus/frontend/www-admin/node_modules/ng-http-loader/ng-http-loader.module.d.ts, resolving symbol NgHttpLoaderModule in /home/tornado-qa1/tornadobus/frontend/www-admin/node_modules/ng-http-loader/ng-http-loader.module.d.ts

It seems that someone, it is using a lambda instead of a exported class but I cannot find where

**Comment by mpalourdio** [comment]
Looks weird to me, as I often run AOT builds inside apps that have this module as dependency.

What if you manually run ``ng build --prod`` inside your project ?

**Comment by EduardoIbarra** [comment]
Thanks for the quick response, I ran it and got the same error, expanded a bit:

> $ ng build --prod
> Date: 2017-08-29T18:52:51.260Z                                                          
> Hash: a3f37ce35debd5dc61f0
> Time: 15981ms
> chunk {0} polyfills.4eb50dee64bc637f384d.bundle.js (polyfills) 64.1 kB {5} [initial] [rendered]
> chunk {1} styles.84fa25d8f15af90bfdcd.bundle.css (styles) 166 kB {5} [initial] [rendered]
> chunk {2} scripts.9e930f66b2210989dda0.bundle.js (scripts) 52 kB {5} [initial] [rendered]
> chunk {3} main.2c22b2cb1402979e0586.bundle.js (main) 411 bytes {4} [initial] [rendered]
> chunk {4} vendor.1af66e21203aac12e2c4.bundle.js (vendor) 211 kB [initial] [rendered]
> chunk {5} inline.d0215cc1e64bb04003e6.bundle.js (inline) 1.47 kB [entry] [rendered]
> 
> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /home/tornado-qa1/tornadobus/frontend/www-admin/node_modules/ng-http-loader/node_modules/@angular/core/core.d.ts, resolving symbol NgHttpLoaderModule in /home/tornado-qa1/tornadobus/frontend/www-admin/node_modules/ng-http-loader/ng-http-loader.module.d.ts, resolving symbol NgHttpLoaderModule in /home/tornado-qa1/tornadobus/frontend/www-admin/node_modules/ng-http-loader/ng-http-loader.module.d.ts
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/tornado-qa1/tornadobus/frontend/www-admin/src'
> resolve './$$_gendir/app/app.module.ngfactory' in '/home/tornado-qa1/tornadobus/frontend/www-admin/src'
>   using description file: /home/tornado-qa1/tornadobus/frontend/www-admin/package.json (relative path: ./src)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /home/tornado-qa1/tornadobus/frontend/www-admin/package.json (relative path: ./src)
>     using description file: /home/tornado-qa1/tornadobus/frontend/www-admin/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory doesn't exist
>       .ts
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
>       as directory
>         /home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory doesn't exist
> [/home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory]
> [/home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory.ts]
> [/home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory.js]
> [/home/tornado-qa1/tornadobus/frontend/www-admin/src/$$_gendir/app/app.module.ngfactory]
>  @ ./src/main.ts 3:0-74
>  @ multi ./src/main.ts

**Comment by mpalourdio** [comment]
This is not this module that causes this error IMO. what does ``ng --version`` outputs ?

**Comment by EduardoIbarra** [comment]
It outputs:

> $ ng --version
>     _                      _                 ____ _     ___
>    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
>   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
>  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
> /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                |___/
> @angular/cli: 1.3.2
> node: 7.4.0
> os: linux x64
> @angular/animations: 4.3.6
> @angular/cdk: 2.0.0-beta.8
> @angular/common: 4.3.6
> @angular/compiler: 4.3.6
> @angular/core: 4.3.6
> @angular/forms: 4.3.6
> @angular/http: 4.3.6
> @angular/material: 2.0.0-beta.8
> @angular/platform-browser: 4.3.6
> @angular/platform-browser-dynamic: 4.3.6
> @angular/router: 4.3.6
> @angular/cli: 1.3.2
> @angular/compiler-cli: 4.3.6

**Comment by mpalourdio** [comment]
could you please post your full package.json ?

**Comment by EduardoIbarra** [comment]
Sure:

```
{
  "name": "www-admin",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.0",
    "@angular/animations": "^4.1.3",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngx-translate/core": "^7.0.0",
    "@ngx-translate/http-loader": "^0.1.0",
    "@types/moment": "^2.13.0",
    "angular-2-dropdown-multiselect": "^1.4.2",
    "angular-2-local-storage": "^1.0.1",
    "angular2-modal": "^2.0.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "moment": "^2.18.1",
    "ng-sidebar": "^5.1.0",
    "ng2-dragula": "^1.5.0",
    "ngx-bootstrap": "^1.6.6",
    "ngx-chips": "^1.5.2",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.6",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

**Comment by mpalourdio** [comment]
Some people report problems solved with ``npm install enhanced-resolve@3.3.0``

Can you give it a try ?

**Comment by mpalourdio** [comment]
`ng-http-loade`r is not in your package.json, is it ?

**Comment by EduardoIbarra** [comment]
No, I think I missed the --save flag. I installed enhanced-resolve  and it seems to have solved the problem. Thanks so much!
