### ISSUE TITLE
angular v5 problem 

### ISSUE THREAD

**Issue by narimanmandi** [mpalourdio/ng-http-loader#80]
according to readme file , the latest version compatible with angular 5 is 0.9.1 but when i use this version in my package.json , angular can't resolve NgHttpLoaderModule 

i am using angular/cli and version of my angular is 5.0.5

**Comment by mpalourdio** [comment]
Take a look at this readme : https://github.com/mpalourdio/ng-http-loader/tree/0.9.1#usage

**Comment by narimanmandi** [comment]
thanks the problem was in my import path 
i use 
import { NgHttpLoaderModule } from 'ng-http-loader/ng-http-loader.module';
and everything is ok now

**Comment by mpalourdio** [comment]
Yes, that's an error that is now fixed with the new bundling made with ng-packagr.

Closing now ! Thanks for feedbacm.
