### ISSUE TITLE
Feature request: Emit events at show and hide

### ISSUE THREAD

**Issue by lalo-mx** [mpalourdio/ng-http-loader#82]
Currently is possible to manually show and hide the loader but due to the animations and delays the operation will not be done immediately.

Would be possible to add an event for those operations?

Outputs
onShow: Emits an event when the loader is visible.
onHide: Emits an event when the load is hidden

**Comment by mpalourdio** [comment]
Already possible bu subscribing to this observable : https://github.com/mpalourdio/ng-http-loader/blob/4f37deedbb5ee917c514db15aec6b89bd1659906/src/lib/services/spinner-visibility.service.ts#L23

**Comment by mpalourdio** [comment]
Closing as feature exists.
