### ISSUE TITLE
Manually hide spinner not working on promise context

### ISSUE THREAD

**Issue by rodrigoic23** [mpalourdio/ng-http-loader#83]
Hi everyone, I'm facing a little issue with this lib.
I have this code:

```
test() {
    this.spinner.show();
    Kinvey.ping().then((res) => {
      console.log(res)
      this.spinner.hide();
    }).catch(err => {
      console.log("ERROR");
      this.spinner.hide();
    })
}
```
on then functions, the console.log line is showed sucessfully, but the spinner is not hiding.
I 've tried with enclosure like this :

```
test() {
    this.spinner.show();
    var that = this;
    Kinvey.ping().then((res) => {
      console.log(res)
      that.spinner.hide();
    }).catch(err => {
      console.log("ERROR");
      that.spinner.hide();
    })
}
```

but it's the same thing.
May I'm missing something?
Thank you

**Comment by rodrigoic23** [comment]
I've solved using  async await, but if someone can help me with the promise approach it would be great.

```
async test() {
    try {
      this.spinner.show();
      const blah = await Kinvey.ping()
      console.log(blah)
      this.spinner.hide()
    } catch (ex) {
      console.log("CATCH", ex)
      this.spinner.hide();
    }
  }

```
Thanks

**Comment by mpalourdio** [comment]
On holidays at the moment, but can you console.log ``this.spinner`` before ``show()`` and before ``hide()`` ?

Also, you ``var that=this`` should be defiend  ``before`` calling ``show()``.

At last, did you try something like this ?

```
test() {
    this.spinner.show();
    Kinvey.ping().then((res) => this.spinner.hide.bind(this.spinner)
}
```

Sorry but I won't have time to give this a serious try before 10 days :/

**Comment by rodrigoic23** [comment]
Hi, thanks for your answer.

> Also, your var that=this should be defined before calling show().
> 
> At last, did you try something like this ?
> 
> test() {
>     this.spinner.show();
>     Kinvey.ping().then((res) => this.spinner.hide.bind(this.spinner)
> }

This is not working. Here is the console log of spinner before show, and before hide inside then context

Before show:
![image](https://user-images.githubusercontent.com/21312654/43277416-5da54ffe-90de-11e8-8acc-1c113e8fcf88.png)

after show - before hide:
![image](https://user-images.githubusercontent.com/21312654/43277562-ccad8240-90de-11e8-96de-1f411379a2c5.png)

after hide:
![image](https://user-images.githubusercontent.com/21312654/43277709-41ae2d9c-90df-11e8-8057-8038dadc47f8.png)

**Comment by mpalourdio** [comment]
Small typo, should be

```
this.spinner.hide().bind(this.spinner)
```

**Comment by mpalourdio** [comment]
Hi !

Sorry for the answer delay. SO, I have just tried the manual toggling in a promise context lke this :

```typescript
runPromise() {
    this.spinner.show();
    this.httpService.runSlowQuery().then(() =>  this.spinner.hide());
}
```

Things work as expected. You should inspect if an HTTP request is not performed in the background. Otherwise, please provide full code for reproducing the issue you are observing.

**Comment by rodrigoic23** [comment]
I really thank you for your work and your answers. I'm thinking on some config or lib of my project blocking this. I've resolved by using async await, is a really good approach for this and for my project. I think you can close this issue, and again thank you.

**Comment by mpalourdio** [comment]
Your welcome, closing as not reproducibleon my side.
