### ISSUE TITLE
Support missing Spinkit spinners

### ISSUE THREAD

**Issue by bunnu** [mpalourdio/ng-http-loader#84]
Hi,

following Spinkit Spinners are missing in ng-http-loader:

- Fading-Circle (https://github.com/tobiasahlin/SpinKit/blob/master/examples/10-fading-circle.html)
- Folding-Cube (https://github.com/tobiasahlin/SpinKit/blob/master/examples/11-folding-cube.html)
- Circle (https://github.com/tobiasahlin/SpinKit/blob/master/examples/8-circle.html)

It would be nice to have these spinners supported.
Thanks in advance.

**Comment by mpalourdio** [comment]
Hi,

that's not possible. please see : https://github.com/mpalourdio/ng-http-loader/pull/70#issuecomment-390916167 and comments after.

Closing as cannot be implemented at the moment. (but possible via the entryComponent feature)
