### ISSUE TITLE
Better handling of synchronous requests

### ISSUE THREAD

**Issue by gnom7** [mpalourdio/ng-http-loader#89]
Please, see [this issue](https://github.com/mpalourdio/ng-http-loader/issues/85) for more info.

**Comment by mpalourdio** [comment]
Thanks !

Here is the test that describe the expected behavior once implemented :

https://github.com/mpalourdio/ng-http-loader/commit/ce0b676653808830d92f19cc179be91f66e82c6e

**Comment by gnom7** [comment]
@mpalourdio 
To answer your question from previous thread: I have looked at test case you wrote and it seems to reflect the feature request. Thanks for it.
Still, I should find the most slow page on the app and set `minDuration` to it's load time to avoid last request from flickering on that page, but then other pages which load way faster will seem to load at the same time as the slowest page in the app. What would you suggest to avoid such problem? Am I missing something?

**Comment by mpalourdio** [comment]
This module can not handle every edge case, hope you understand. And I want to keep it simple !

If you want to handle different minimum duration, you can declare the <ng-http-loader> at each component level, not at your root application level. This way, you can have multiple ng-http-loader instance, so you can set multiple minDuration when needed.

**Comment by gnom7** [comment]
I'd not call this use case 'edge case', it looks very naturally to me. Can you please provide some use cases when someone will prefer `minDuration` over `minExtraDuration` described in previous thread? As you said `minDuration` was introduced to handle exactly this case, but it seems to me that `minExtraDuration` does it better.

**Comment by mpalourdio** [comment]
I will focus on this feature request for the moment. AS I said, you can still declare multiple instances, adn if not convenient enough (can be boilerplate for big apps), you can set a different `minDuration` value by injecting NgHttpLoaderComponent as `@ViewChild`.

**Comment by gnom7** [comment]
As you wish, of course, just wondering 'why'.

**Comment by mpalourdio** [comment]
For the moment, I cannot really understand what your `minExtraDuration` option will add once this feature request twill be implemented, sorry :/

**Comment by gnom7** [comment]
I may try to explain it in a better way, if you are open for it.

**Comment by mpalourdio** [comment]
Sure :)

**Comment by gnom7** [comment]
Drawbacks of current approach with `minDuration`:
1) Should be defined for each page to prevent slowing down of faster pages due to blinking issues on slower ones.
2) After first point, still, many users with slower internet connection will experience the issue as `minDuration` for them will be not high enough.
3) Let's change you test so, that second request runs for 100ms, after that spinner will be shown extra 700ms after request already have ended, that's much, and this will happen in real world.

My proposal is to change how `minDuration` works, let's count not from when spinner starts to be visible, but when it ends (meaning the request ends), that's why I called it `minExtraDuration`, this way you may specify say 5ms value for this property, this means that after request ended spinners will be still visible 5ms extra time, if in this 5ms new requests are triggered spinner will be still visible and this will prevent spinner from blinking, each new request will re-trigger spinner and `minExtraDuration`. This way we will avoid all 3 issues above in the following way:
1) We define it once as `minExtraDuration` is really global property, not same as `minDuration` which differs from page to page.
2) It doesn't depend on internet connection quality as 5ms is time to craft new request based on new data arrived _after_ previous request ended, so it has to be with js execution time, which is generally faster (~5ms) compared to http request execution time.
3) Bunch of requests fill be executed only ~5ms extra time (within the error of the execution time of the request itself), in your test this will mean that after all requests flushed you should wait only 5ms extra instead of 700ms.

Would you be so kind to describe how you see my proposal? May be me or you missing something?

**Comment by mpalourdio** [comment]
Thanks for this great clarification, I understand much better now :) Let me please clarify some points.
>  Should be defined for each page to prevent slowing down of faster pages due to blinking issues on slower ones.

Not necessarily TBH. Could be specified only on slow pages, or set to 0 on fast pages. I agree, that's not very convenient, but it is possible via @ViewChild.

>    After first point, still, many users with slower internet connection will experience the issue as `minDuration` for them will be not high enough.

That's not how this option works exactly. If `minDuration` is set to 500ms, and for many reasons your HTTP requests ends after, let's say, 800 ms, at exactly 800ms, the spinner will hide.

>    Let's change you test so, that second request runs for 100ms, after that spinner will be shown extra 700ms after request already have ended, that's much, and this will happen in real world.

Of course, that's the culprit of this option.
> 
> My proposal is to change how `minDuration` works,

For BC reasons, I will not change nor this option's behavior, neither its name. I rage myself too much about the nodejs ecosystem not beeing semver compliant =)

> let's count not from when spinner starts to be visible, but when it ends (meaning the request ends), that's why I called it `minExtraDuration`, this way you may specify say 5ms value for this property, this means that after request ended spinners will be still visible 5ms extra time, if in this 5ms new requests are triggered spinner will be still visible and this will prevent spinner from blinking, each new request will re-trigger spinner and `minExtraDuration`. 

I definitely LIKE this idea. `extraDuration` would fit better IMO. WDYT ?

There's still some points to address. What about mixing options ? What if you mix minDuration and extraDuration. What if `debounceDelay` is specified, particularly in case another http request is performed just after. 

This will not be simple to address, and will need some very robust unit tests. That's not impossible of course, but I will take some time and some refactoring to implement.

But I like this proposal ! Thanks a lot !

**Comment by gnom7** [comment]
Yes, actually I think that `minDuration` feature is great to have (to avoid blinks in case request runs 105ms with `debounceDelay` set to 100ms we will have blink for 5ms -- not good, this is real use case of `minDuration` I believe), so ideally I'd like to add `extraDuration`, not replace `minDuration`, possibly even without breaking changes, so it may be released as `3.1.0` version.
> Not necessarily TBH. Could be specified only on slow pages, or set to 0 on fast pages. I agree, that's not very convenient, but it is possible via @ViewChild.

I agree with you, but still, it seems dirty to me.
> That's not how this option works exactly. If minDuration is set to 500ms, and for many reasons your HTTP requests ends after, let's say, 800 ms, at exactly 800ms, the spinner will hide.

Got it, but I was talking about slow and fast connections, if you set `minDuration` to say 200ms and this works great for you (150ms + 2ms + 100ms -- no blink), some of your users with worse internet connection will still suffer blinks issue (210ms + 2ms + 150ms -- woops, blink).
> For BC reasons, I will not change nor this option's behavior, neither its name. I rage myself too much about the nodejs ecosystem not beeing semver compliant =)

Totally agree, sorry my wording, I'd like much more to _add_ `extraDuration` property. (Though you can just follow semver and make v4, it is up to you to follow or not).
> I definitely LIKE this idea. extraDuration would fit better IMO. WDYT ?

For my use case it will be great solution I think.
> There's still some points to address. What about mixing options ? What if you mix minDuration and extraDuration.

I think that as they both intended to prolongate time when spinner is visible the latest wins (I think it will be achieved in natural way just by implementing new `extraDuration` property).
> What if debounceDelay is specified, particularly in case another http request is performed just after.

I think that as `debounceDelay` is intended to hide spinner on fast pages/elements it should apply only to requests which run when we have no spinner displayed, after it get displayed new requests should not be delayed, but directly affect time current spinner is shown.

Let me know if you have some concerns about my proposal or help is needed (though I'm not very proficient with rxjs).

**Comment by mpalourdio** [comment]
First integration has landed in https://github.com/mpalourdio/ng-http-loader/releases/tag/3.1.0-beta.0
