### ISSUE TITLE
Unable to access SpinnerVisibilityService

### ISSUE THREAD

**Issue by shivamsriva31093** [mpalourdio/ng-http-loader#99]
I wanted to manually handle the loader as shown in the readme. However, I cannot access the SpinnerVisibilityService class itself. The version used is 0.3.4  with angular 4.

![screenshot 3](https://user-images.githubusercontent.com/17279956/47015337-50f87980-d16a-11e8-86dd-7f0b8e90f88a.png)

**Comment by mpalourdio** [comment]
You're using a VERY outdated version. This feature has been introduced in [v0.8.0](https://github.com/mpalourdio/ng-http-loader/blob/master/CHANGELOG.md#v080) for the first time, and is only angular 5 compatible.

**Comment by shivamsriva31093** [comment]
Thanks @mpalourdio .
